export const quizQuestions = [
  { fi: "ubratsya - убраться", answer: "To clean", options: ["To clean","To cook","To sleep"] },
  { fi: "pylesos - пылесос", answer: "Vacuum cleaner", options: ["Vacuum cleaner","Mop","Bucket"] },
  { fi: "kasha - каша", answer: "Slush", options: ["Slush","Ice","Fog"] },
  { fi: "prachechnaya - прачечная", answer: "Laundry room", options: ["Laundry room","Bathroom","Garage"] },
  { fi: "kladovka - кладовка", answer: "Cupboard / closet", options: ["Cupboard / closet","Window","Radiator"] },
  { fi: "kovyor - ковёр", answer: "Rug / mat", options: ["Rug / mat","Curtain","Lamp"] },
  { fi: "kovrobivalka - ковробивалка", answer: "Rug beater", options: ["Rug beater","Broom","Dustpan"] },
  { fi: "pyl - пыль", answer: "Dust", options: ["Dust","Soap","Paint"] },
  { fi: "posudomoechnaya mashina - посудомоечная машина", answer: "Dishwasher", options: ["Dishwasher","Microwave","Fridge"] },
  { fi: "stiralnaya mashina - стиральная машина", answer: "Washing machine", options: ["Washing machine","Dryer only","Oven"] },
  { fi: "sushilnyy baraban - сушильный барабан", answer: "Dryer (tumble dryer)", options: ["Dryer (tumble dryer)","Fan","Heater"] },
  { fi: "posuda - посуда", answer: "Dishes", options: ["Dishes","Groceries","Towels"] },
  { fi: "vilka - вилка", answer: "Fork", options: ["Fork","Spoon","Plate"] },
  { fi: "lozhka - ложка", answer: "Spoon", options: ["Spoon","Knife","Glass"] },
  { fi: "nozh - нож", answer: "Knife", options: ["Knife","Fork","Pot"] },
  { fi: "zhidkost dlya posudy - жидкость для посуды", answer: "Dish detergent", options: ["Dish detergent","Shampoo","Toothpaste"] },
  { fi: "stiralnyy poroshok - стиральный порошок", answer: "Laundry powder / detergent", options: ["Laundry powder / detergent","Salt","Sugar"] },
  { fi: "tryapka - тряпка", answer: "Rag / cloth", options: ["Rag / cloth","Shoe","Hat"] },
  { fi: "gubka - губка", answer: "Sponge", options: ["Sponge","Brush","Bucket"] },
  { fi: "polka - полка", answer: "Shelf", options: ["Shelf","Door","Floor"] },
  { fi: "balkon - балкон", answer: "Balcony", options: ["Balcony","Basement","Attic"] },
  { fi: "sosed - сосед", answer: "Neighbor", options: ["Neighbor","Landlord","Courier"] },
  { fi: "ovcharka - овчарка", answer: "Alsatian / German shepherd", options: ["Alsatian / German shepherd","Cat","Rabbit"] },
  { fi: "provetrivat - проветривать", answer: "To air out / ventilate", options: ["To air out / ventilate","To seal","To wallpaper"] },
  { fi: "vyklyuchat - выключать", answer: "To turn off / switch off", options: ["To turn off / switch off","To break","To buy"] },
  { fi: "programma - программа", answer: "Program (wash cycle)", options: ["Program (wash cycle)","Remote","Channel"] },
  { fi: "baraban - барабан", answer: "Drum (of a machine)", options: ["Drum (of a machine)","Wheel","Bell"] },
  { fi: "rakovina - раковина", answer: "Sink / basin", options: ["Sink / basin","Stove","Oven"] },
  { fi: "dovolnyy - довольный", answer: "Satisfied / content", options: ["Satisfied / content","Angry","Confused"] },
  { fi: "akkuratnyy - аккуратный", answer: "Tidy / neat", options: ["Tidy / neat","Broken","Empty"] },
  { fi: "gryaznyy - грязный", answer: "Dirty", options: ["Dirty","Expensive","Heavy"] },
  { fi: "podval - подвал", answer: "Cellar / basement", options: ["Cellar / basement","Roof","Attic"] },
  { fi: "spisok pokupok - список покупок", answer: "Shopping list", options: ["Shopping list","Recipe","Invoice"] },
  { fi: "vytryasti - вытрясти", answer: "To shake", options: ["To shake","To fold","To iron"] },
  { fi: "chikhat - чихать", answer: "To sneeze", options: ["To sneeze","To cough","To yawn"] },
  { fi: "temperatura - температура", answer: "Fever / temperature", options: ["Fever / temperature","Cough","Rash"] },
  { fi: "mokryy sneg - мокрый снег", answer: "Sleet", options: ["Sleet","Hail","Thunder"] },
  { fi: "tsvetnoy - цветной", answer: "Colored", options: ["Colored","Invisible","Wooden"] },
  { fi: "mokryy - мокрый", answer: "Wet", options: ["Wet","Dry","Hot"] },
  { fi: "tyazhyolyy - тяжёлый", answer: "Heavy", options: ["Heavy","Light","Soft"] },
  { fi: "pochti - почти", answer: "Almost", options: ["Almost","Never","Always"] },
  { fi: "sluchayno - случайно", answer: "By chance / at random", options: ["By chance / at random","On purpose","Tomorrow"] },
  { fi: "vsyo yeshchyo - всё ещё", answer: "Still", options: ["Still","Already","Never"] },
  { fi: "rukami - руками", answer: "By hand", options: ["By hand","By machine","By mail"] },
  { fi: "razdrazhayushchiy - раздражающий", answer: "Annoying", options: ["Annoying","Pleasant","Silent"] },
  { fi: "uspokaivayushchiy - успокаивающий", answer: "Calming / soothing", options: ["Calming / soothing","Loud","Dangerous"] },
  { fi: "shumnyy - шумный", answer: "Noisy / loud", options: ["Noisy / loud","Quiet","Dark"] },
  { fi: "trevoga - тревога", answer: "Emergency / worry (ei hätää = no worries)", options: ["Emergency / worry (ei hätää = no worries)","Party","Gift"] },
  { fi: "dobryy - добрый", answer: "Kind / gentle", options: ["Kind / gentle","Mean","Shy"] },
  { fi: "seryozno - серьёзно", answer: "Seriously", options: ["Seriously","Quickly","Quietly"] },
  { fi: "vybivat - выбивать", answer: "To beat (a rug)", options: ["To beat (a rug)","To bake","To call"] },
  { fi: "pylesosit - пылесосить", answer: "To vacuum", options: ["To vacuum","To mop","To paint"] },
  { fi: "sredstvo dlya uborki - средство для уборки", answer: "Cleaning supply", options: ["Cleaning supply","Food item","Tool"] },
  { fi: "pylesbornik - пылесборник", answer: "Dust bag (for vacuum)", options: ["Dust bag (for vacuum)","Trash bag","Wallet"] },
  { fi: "polnyy - полный", answer: "Full", options: ["Full","Empty","Open"] },
  { fi: "naruzhu - наружу", answer: "Out / outside", options: ["Out / outside","Upstairs","Inside"] },
  { fi: "vnutr - внутрь", answer: "Inside / in", options: ["Inside / in","Outside","Under"] },
  { fi: "gotovyy - готовый", answer: "Ready / finished", options: ["Ready / finished","Broken","Lost"] },
  { fi: "ustalyy - усталый", answer: "Tired", options: ["Tired","Hungry","Angry"] },
  { fi: "chistyy - чистый", answer: "Clean", options: ["Clean","Dirty","Old"] },
  { fi: "svezhiy - свежий", answer: "Fresh", options: ["Fresh","Stale","Sour"] },
  { fi: "televizor - телевизор", answer: "Television / TV", options: ["Television / TV","Radio","Phone"] },
  { fi: "pol - пол", answer: "Floor", options: ["Floor","Ceiling","Wall"] },
  { fi: "divan - диван", answer: "Sofa / couch", options: ["Sofa / couch","Table","Chair"] },
  { fi: "okno - окно", answer: "Window", options: ["Window","Door","Wall"] },
  { fi: "kukhnya - кухня", answer: "Kitchen", options: ["Kitchen","Bedroom","Hallway"] },
  { fi: "kvartira - квартира", answer: "Apartment / flat", options: ["Apartment / flat","Office","Shop"] },
  { fi: "lift - лифт", answer: "Elevator / lift", options: ["Elevator / lift","Stairs","Escalator"] },
  { fi: "bronirovat - бронировать", answer: "To reserve / book", options: ["To reserve / book","To cancel","To forget"] },
  { fi: "vozvrashchatsya - возвращаться", answer: "To return / go back", options: ["To return / go back","To leave","To hide"] },
  { fi: "platit - платить", answer: "To pay", options: ["To pay","To steal","To borrow"] },
  { fi: "pokupat - покупать", answer: "To buy", options: ["To buy","To sell","To rent"] },
  { fi: "peremeshchat - перемещать", answer: "To move / transfer", options: ["To move / transfer","To break","To hide"] }
];
