export const quizQuestions = [
  { fi: "Siivota", answer: "To clean", options: ["To clean","To cook","To sleep"] },
  { fi: "Imuri", answer: "Vacuum cleaner", options: ["Vacuum cleaner","Mop","Bucket"] },
  { fi: "Loska", answer: "Slush", options: ["Slush","Ice","Fog"] },
  { fi: "Pesutupa", answer: "Laundry room", options: ["Laundry room","Bathroom","Garage"] },
  { fi: "Komero", answer: "Cupboard / closet", options: ["Cupboard / closet","Window","Radiator"] },
  { fi: "Matto", answer: "Rug / mat", options: ["Rug / mat","Curtain","Lamp"] },
  { fi: "Mattopiiska", answer: "Rug beater", options: ["Rug beater","Broom","Dustpan"] },
  { fi: "Pöly", answer: "Dust", options: ["Dust","Soap","Paint"] },
  { fi: "Tiskikone", answer: "Dishwasher", options: ["Dishwasher","Microwave","Fridge"] },
  { fi: "Pesukone", answer: "Washing machine", options: ["Washing machine","Dryer only","Oven"] },
  { fi: "Kuivausrumpu", answer: "Dryer (tumble dryer)", options: ["Dryer (tumble dryer)","Fan","Heater"] },
  { fi: "Astiat", answer: "Dishes", options: ["Dishes","Groceries","Towels"] },
  { fi: "Haarukka", answer: "Fork", options: ["Fork","Spoon","Plate"] },
  { fi: "Lusikka", answer: "Spoon", options: ["Spoon","Knife","Glass"] },
  { fi: "Veitsi", answer: "Knife", options: ["Knife","Fork","Pot"] },
  { fi: "Tiskiaine", answer: "Dish detergent", options: ["Dish detergent","Shampoo","Toothpaste"] },
  { fi: "Pesujauhe", answer: "Laundry powder / detergent", options: ["Laundry powder / detergent","Salt","Sugar"] },
  { fi: "Riepu", answer: "Rag / cloth", options: ["Rag / cloth","Shoe","Hat"] },
  { fi: "Sieni", answer: "Sponge", options: ["Sponge","Brush","Bucket"] },
  { fi: "Hylly", answer: "Shelf", options: ["Shelf","Door","Floor"] },
  { fi: "Parveke", answer: "Balcony", options: ["Balcony","Basement","Attic"] },
  { fi: "Naapuri", answer: "Neighbor", options: ["Neighbor","Landlord","Courier"] },
  { fi: "Susikoira", answer: "Alsatian / German shepherd", options: ["Alsatian / German shepherd","Cat","Rabbit"] },
  { fi: "Tuulettaa", answer: "To air out / ventilate", options: ["To air out / ventilate","To seal","To wallpaper"] },
  { fi: "Sammuttaa", answer: "To turn off / switch off", options: ["To turn off / switch off","To break","To buy"] },
  { fi: "Ohjelma", answer: "Program (wash cycle)", options: ["Program (wash cycle)","Remote","Channel"] },
  { fi: "Rumpu", answer: "Drum (of a machine)", options: ["Drum (of a machine)","Wheel","Bell"] },
  { fi: "Allas", answer: "Sink / basin", options: ["Sink / basin","Stove","Oven"] },
  { fi: "Tyytyväinen", answer: "Satisfied / content", options: ["Satisfied / content","Angry","Confused"] },
  { fi: "Siisti", answer: "Tidy / neat", options: ["Tidy / neat","Broken","Empty"] },
  { fi: "Likainen", answer: "Dirty", options: ["Dirty","Expensive","Heavy"] },
  { fi: "Kellari", answer: "Cellar / basement", options: ["Cellar / basement","Roof","Attic"] },
  { fi: "Ostoslista", answer: "Shopping list", options: ["Shopping list","Recipe","Invoice"] },
  { fi: "Ravistaa", answer: "To shake", options: ["To shake","To fold","To iron"] },
  { fi: "Aivastaa", answer: "To sneeze", options: ["To sneeze","To cough","To yawn"] },
  { fi: "Kuume", answer: "Fever / temperature", options: ["Fever / temperature","Cough","Rash"] },
  { fi: "Räntä", answer: "Sleet", options: ["Sleet","Hail","Thunder"] },
  { fi: "Värillinen", answer: "Colored", options: ["Colored","Invisible","Wooden"] },
  { fi: "Märkä", answer: "Wet", options: ["Wet","Dry","Hot"] },
  { fi: "Raskas", answer: "Heavy", options: ["Heavy","Light","Soft"] },
  { fi: "Melkein", answer: "Almost", options: ["Almost","Never","Always"] },
  { fi: "Sattumalta", answer: "By chance / at random", options: ["By chance / at random","On purpose","Tomorrow"] },
  { fi: "Edelleen", answer: "Still", options: ["Still","Already","Never"] },
  { fi: "Käsin", answer: "By hand", options: ["By hand","By machine","By mail"] },
  { fi: "Ärsyttävä", answer: "Annoying", options: ["Annoying","Pleasant","Silent"] },
  { fi: "Rauhoittava", answer: "Calming / soothing", options: ["Calming / soothing","Loud","Dangerous"] },
  { fi: "Äänekäs", answer: "Noisy / loud", options: ["Noisy / loud","Quiet","Dark"] },
  { fi: "Hätä", answer: "Emergency / worry (ei hätää = no worries)", options: ["Emergency / worry (ei hätää = no worries)","Party","Gift"] },
  { fi: "Kiltti", answer: "Kind / gentle", options: ["Kind / gentle","Mean","Shy"] },
  { fi: "Vakavasti", answer: "Seriously", options: ["Seriously","Quickly","Quietly"] },
  { fi: "Piiskata", answer: "To beat (a rug)", options: ["To beat (a rug)","To bake","To call"] },
  { fi: "Imuroida", answer: "To vacuum", options: ["To vacuum","To mop","To paint"] },
  { fi: "Siivoustarvike", answer: "Cleaning supply", options: ["Cleaning supply","Food item","Tool"] },
  { fi: "Pölypussi", answer: "Dust bag (for vacuum)", options: ["Dust bag (for vacuum)","Trash bag","Wallet"] },
  { fi: "Täynnä", answer: "Full", options: ["Full","Empty","Open"] },
  { fi: "Ulos", answer: "Out / outside", options: ["Out / outside","Upstairs","Inside"] },
  { fi: "Sisään", answer: "Inside / in", options: ["Inside / in","Outside","Under"] },
  { fi: "Valmis", answer: "Ready / finished", options: ["Ready / finished","Broken","Lost"] },
  { fi: "Väsynyt", answer: "Tired", options: ["Tired","Hungry","Angry"] },
  { fi: "Puhdas", answer: "Clean", options: ["Clean","Dirty","Old"] },
  { fi: "Raikas", answer: "Fresh", options: ["Fresh","Stale","Sour"] },
  { fi: "Televisio", answer: "Television / TV", options: ["Television / TV","Radio","Phone"] },
  { fi: "Lattia", answer: "Floor", options: ["Floor","Ceiling","Wall"] },
  { fi: "Sohva", answer: "Sofa / couch", options: ["Sofa / couch","Table","Chair"] },
  { fi: "Ikkuna", answer: "Window", options: ["Window","Door","Wall"] },
  { fi: "Keittiö", answer: "Kitchen", options: ["Kitchen","Bedroom","Hallway"] },
  { fi: "Asunto", answer: "Apartment / flat", options: ["Apartment / flat","Office","Shop"] },
  { fi: "Hissi", answer: "Elevator / lift", options: ["Elevator / lift","Stairs","Escalator"] },
  { fi: "Varata", answer: "To reserve / book", options: ["To reserve / book","To cancel","To forget"] },
  { fi: "Palata", answer: "To return / go back", options: ["To return / go back","To leave","To hide"] },
  { fi: "Maksaa", answer: "To pay", options: ["To pay","To steal","To borrow"] },
  { fi: "Ostaa", answer: "To buy", options: ["To buy","To sell","To rent"] },
  { fi: "Siirtää", answer: "To move / transfer", options: ["To move / transfer","To break","To hide"] }
];
