export const quizQuestions = [
  { fi: "podtverdit lichnost - подтвердить личность", answer: "To identify oneself / authenticate", options: ["To identify oneself / authenticate", "To browse", "To negotiate"] },
  { fi: "dannye internet-banka - данные интернет-банка", answer: "Online banking credentials", options: ["Online banking credentials", "Store loyalty points", "Travel documents"] },
  { fi: "ozhidanie v ocheredi - ожидание в очереди", answer: "Queuing / waiting in line", options: ["Queuing / waiting in line", "Scheduling", "Delivering"] },
  { fi: "primerno - примерно", answer: "Approximately / estimated", options: ["Approximately / estimated", "Precisely", "Immediately"] },
  { fi: "variant - вариант", answer: "Option / alternative", options: ["Option / alternative", "Contract", "Receipt"] },
  { fi: "kredit - кредит", answer: "Loan", options: ["Loan", "Invoice", "Discount"] },
  { fi: "onlayn-servisy - онлайн-сервисы", answer: "Online services", options: ["Online services", "Postal services", "Cleaning services"] },
  { fi: "servis kart - сервис карт", answer: "Card services", options: ["Card services", "Mortgage services", "Support hotline"] },
  { fi: "nazhat tri - нажать три", answer: "To press three", options: ["To press three", "To mute the call", "To hang up"] },
  { fi: "dlit'sya - длиться", answer: "To take (time) / last", options: ["To take (time) / last", "To reserve", "To attach"] },
  { fi: "v ofis - в офис", answer: "To the office", options: ["To the office", "To the station", "To the airport"] },
  { fi: "privetstvovat - приветствовать", answer: "To greet", options: ["To greet", "To interrupt", "To nominate"] },
  { fi: "perevesti zvonok - перевести звонок", answer: "To transfer/connect (a call)", options: ["To transfer/connect (a call)", "To translate", "To postpone"] },
  { fi: "otdel - отдел", answer: "Department", options: ["Department", "Province", "Warehouse shelf"] },
  { fi: "obyasnit situatsiyu - объяснить ситуацию", answer: "To explain the situation", options: ["To explain the situation", "To print the ticket", "To cancel the order"] },
  { fi: "svobodnoe vremya - свободное время", answer: "Available appointment slots", options: ["Available appointment slots", "Holiday requests", "Office chairs"] },
  { fi: "dolgoe vremya - долгое время", answer: "For a long time", options: ["For a long time", "Every morning", "At once"] },
  { fi: "cherez mesyats - через месяц", answer: "In a month", options: ["In a month", "Last week", "Twice a day"] },
  { fi: "vzdykhat - вздыхать", answer: "To sigh", options: ["To sigh", "To whisper", "To argue"] },
  { fi: "sotrudnik - сотрудник", answer: "Employee / worker", options: ["Employee / worker", "Customer", "Visitor"] },
  { fi: "v sredu - в среду", answer: "On Wednesday", options: ["On Wednesday", "On Friday", "At midnight"] },
  { fi: "zavershit zvonok - завершить звонок", answer: "To end a call", options: ["To end a call", "To miss a call", "To record a call"] },
  { fi: "rabochiy stol - рабочий стол", answer: "Workstation / desk", options: ["Workstation / desk", "Ticket counter", "Loading dock"] },
  { fi: "zarabotat - заработать", answer: "To earn", options: ["To earn", "To request", "To estimate"] },
  { fi: "otpusknoy den - отпускной день", answer: "Vacation day", options: ["Vacation day", "Work shift", "Tax day"] },
  { fi: "kivnut - кивнуть", answer: "To nod", options: ["To nod", "To laugh", "To hesitate"] },
  { fi: "neoplachivaemyy - неоплачиваемый", answer: "Unpaid", options: ["Unpaid", "Overdue", "Optional"] },
  { fi: "vykhodnoy den - выходной день", answer: "Day off", options: ["Day off", "Payday", "Exam day"] },
  { fi: "bankovskiy vopros - банковский вопрос", answer: "Bank-related matter", options: ["Bank-related matter", "Medical referral", "Traffic ticket"] },
  { fi: "vazhnyy - важный", answer: "Important", options: ["Important", "Temporary", "Automatic"] },
];

