export const quizQuestions = [
  { fi: "Tunnistautua", answer: "To identify oneself / authenticate", options: ["To identify oneself / authenticate", "To browse", "To negotiate"] },
  { fi: "Verkkopankkitunnukset", answer: "Online banking credentials", options: ["Online banking credentials", "Store loyalty points", "Travel documents"] },
  { fi: "Jonotus", answer: "Queuing / waiting in line", options: ["Queuing / waiting in line", "Scheduling", "Delivering"] },
  { fi: "Arviolta", answer: "Approximately / estimated", options: ["Approximately / estimated", "Precisely", "Immediately"] },
  { fi: "Vaihtoehto", answer: "Option / alternative", options: ["Option / alternative", "Contract", "Receipt"] },
  { fi: "Laina", answer: "Loan", options: ["Loan", "Invoice", "Discount"] },
  { fi: "Verkkopalvelut", answer: "Online services", options: ["Online services", "Postal services", "Cleaning services"] },
  { fi: "Korttipalvelut", answer: "Card services", options: ["Card services", "Mortgage services", "Support hotline"] },
  { fi: "Kolmosta painaa", answer: "To press three", options: ["To press three", "To mute the call", "To hang up"] },
  { fi: "Kestää", answer: "To take (time) / last", options: ["To take (time) / last", "To reserve", "To attach"] },
  { fi: "Toimistolle", answer: "To the office", options: ["To the office", "To the station", "To the airport"] },
  { fi: "Tervehtiä", answer: "To greet", options: ["To greet", "To interrupt", "To nominate"] },
  { fi: "Yhdistää", answer: "To transfer/connect (a call)", options: ["To transfer/connect (a call)", "To translate", "To postpone"] },
  { fi: "Osasto", answer: "Department", options: ["Department", "Province", "Warehouse shelf"] },
  { fi: "Selittää tilanne", answer: "To explain the situation", options: ["To explain the situation", "To print the ticket", "To cancel the order"] },
  { fi: "Vapaita aikoja", answer: "Available appointment slots", options: ["Available appointment slots", "Holiday requests", "Office chairs"] },
  { fi: "Pitkään aikaan", answer: "For a long time", options: ["For a long time", "Every morning", "At once"] },
  { fi: "Kuukauden päästä", answer: "In a month", options: ["In a month", "Last week", "Twice a day"] },
  { fi: "Huokaista", answer: "To sigh", options: ["To sigh", "To whisper", "To argue"] },
  { fi: "Työntekijä", answer: "Employee / worker", options: ["Employee / worker", "Customer", "Visitor"] },
  { fi: "Keskiviikkona", answer: "On Wednesday", options: ["On Wednesday", "On Friday", "At midnight"] },
  { fi: "Lopettaa puhelu", answer: "To end a call", options: ["To end a call", "To miss a call", "To record a call"] },
  { fi: "Työpiste", answer: "Workstation / desk", options: ["Workstation / desk", "Ticket counter", "Loading dock"] },
  { fi: "Ansaita", answer: "To earn", options: ["To earn", "To request", "To estimate"] },
  { fi: "Lomapäivä", answer: "Vacation day", options: ["Vacation day", "Work shift", "Tax day"] },
  { fi: "Nyökätä", answer: "To nod", options: ["To nod", "To laugh", "To hesitate"] },
  { fi: "Palkaton", answer: "Unpaid", options: ["Unpaid", "Overdue", "Optional"] },
  { fi: "Vapaapäivä", answer: "Day off", options: ["Day off", "Payday", "Exam day"] },
  { fi: "Pankkiasia", answer: "Bank-related matter", options: ["Bank-related matter", "Medical referral", "Traffic ticket"] },
  { fi: "Tärkeä", answer: "Important", options: ["Important", "Temporary", "Automatic"] },
];

