export const quizQuestions = [
  { fi: "viheltäen", answer: "whistling", options: ["whistling", "whispering", "running"] },
  { fi: "matkalaukku", answer: "suitcase", options: ["suitcase", "briefcase", "backpack"] },
  { fi: "iloiselta", answer: "happy", options: ["happy", "angry", "tired"] },
  { fi: "muuttaa takaisin", answer: "move back", options: ["move back", "move away", "stay overnight"] },
  { fi: "nyökkää", answer: "nods", options: ["nods", "shouts", "laughs"] },
  { fi: "lattialle", answer: "onto the floor", options: ["onto the floor", "to the wall", "to the ceiling"] },
  { fi: "siivota", answer: "to clean", options: ["to clean", "to cook", "to drive"] },
  { fi: "imuroida", answer: "to vacuum", options: ["to vacuum", "to iron", "to rinse"] },
  { fi: "pyyhin pölyt", answer: "I wiped the dust", options: ["I wiped the dust", "I watered the flowers", "I packed the bag"] },
  { fi: "työpiste", answer: "workstation", options: ["workstation", "meeting room", "hallway"] },
  { fi: "sähköposti", answer: "email", options: ["email", "calendar", "spreadsheet"] },
  { fi: "näppäimistö", answer: "keyboard", options: ["keyboard", "monitor", "mousepad"] },
  { fi: "matkalasku", answer: "travel expense report", options: ["travel expense report", "train schedule", "project contract"] },
  { fi: "kuitit", answer: "receipts", options: ["receipts", "invoices", "tickets"] },
  { fi: "lomake", answer: "form", options: ["form", "folder", "password"] },
  { fi: "tulostin", answer: "printer", options: ["printer", "speaker", "router"] },
  { fi: "skanneri", answer: "scanner", options: ["scanner", "camera", "server"] },
  { fi: "häikäisee", answer: "glares / dazzles", options: ["glares / dazzles", "warms", "freezes"] },
  { fi: "verhot", answer: "curtains", options: ["curtains", "blinds", "carpets"] },
  { fi: "virheilmoitus", answer: "error message", options: ["error message", "welcome message", "warning label"] },
  { fi: "hyväksy", answer: "accept", options: ["accept", "delete", "print"] },
  { fi: "muodossa", answer: "in format", options: ["in format", "in color", "in order"] },
  { fi: "kuvakaappaus", answer: "screenshot", options: ["screenshot", "scan", "attachment"] },
  { fi: "syöttää", answer: "to input / submit", options: ["to input / submit", "to export", "to rename"] },
  { fi: "lopulta", answer: "finally", options: ["finally", "suddenly", "immediately"] },
  { fi: "epämuodollinen", answer: "informal", options: ["informal", "urgent", "weekly"] },
  { fi: "kokous", answer: "meeting", options: ["meeting", "deadline", "invoice"] },
  { fi: "tekoälyagentit", answer: "AI agents", options: ["AI agents", "database admins", "support tickets"] },
  { fi: "tietoturva", answer: "data security", options: ["data security", "user interface", "budget planning"] },
  { fi: "erillinen", answer: "separate", options: ["separate", "public", "broken"] },
  { fi: "ympäristö", answer: "environment", options: ["environment", "department", "browser"] },
  { fi: "hiekkalaatikko", answer: "sandbox", options: ["sandbox", "firewall", "keyboard shortcut"] },
  { fi: "oikeudet", answer: "permissions", options: ["permissions", "warnings", "receipts"] },
  { fi: "tapahtua", answer: "to happen", options: ["to happen", "to compile", "to download"] },
  { fi: "prototyyppi", answer: "prototype", options: ["prototype", "production release", "hotfix"] },
  { fi: "ensimmäinen", answer: "first", options: ["first", "last", "second"] },
  { fi: "oikeastaan", answer: "actually", options: ["actually", "usually", "already"] },
  { fi: "ainakin", answer: "at least", options: ["at least", "never", "almost"] },
  { fi: "turvallinen", answer: "safe", options: ["safe", "expensive", "fast"] },
  { fi: "jatketaan", answer: "let's continue", options: ["let's continue", "let's cancel", "let's deploy"] },
];
