export const chapterTitles = {
  1: "V aeroportu - At the airport",
  2: "V lifte - In the elevator",
  3: "V magazine odezhdy - In the clothing store",
  4: "Pervyy rabochiy den - First day at work",
  5: "Odin doma - Home alone",
  6: "Remont trub - Pipe renovation",
  7: "Futsal - Futsal",
  8: "Razgovor s mamoy - Call with mom",
  9: "Na ldu - On the ice",
  10: "V magazine - In the store",
  11: "Pannacotta - Pannacotta",
  12: "Uzhin - Dinner",
  13: "Biblioteka - Library",
  14: "Lyzhi - Skiing",
  15: "Zvonok v bank - Calling the bank",
  16: "Turku - Turku",
  17: "Vrach - Doctor",
  18: "Apteka - Pharmacy",
  19: "Den uborki - Cleaning day",
  20: "Razgovor o razvitii - Development discussion",
  21: "Kupanie v prorubi - Ice swimming",
  22: "Komandirovka zavtra - Work trip tomorrow",
  23: "V Shvetsii - In Sweden",
  24: "V trenazhernom zale - At the gym",
  25: "Svidanie - A date",
  26: "Vesna prikhodit - Spring arrives",
  27: "Den v ofise - A day at the office"
};
