export const chapterTitles = {
  1: "Lentokentällä - At the airport",
  2: "Hississä - In the elevator",
  3: "Vaatekaupassa - In the clothing store",
  4: "Ensimmäinen työpäivä - First day at work",
  5: "Yksin kotona - Home alone",
  6: "Putkiremontti - Pipe renovation",
  7: "Futsal - Futsal",
  8: "Puhelu äidin kanssa - Call with mom",
  9: "Jäällä - On the ice",
  10: "Kaupassa - In the store",
  11: "Pannacotta - Pannacotta",
  12: "Päivällinen - Dinner",
  13: "Kirjasto - Library",
  14: "Hiihto - Skiing",
  15: "Puhelu pankkiin - Calling the bank",
  16: "Turku - Turku",
  17: "Lääkäri - Doctor",
  18: "Apteekki - Pharmacy",
  19: "Siivouspäivä - Cleaning day",
  20: "Kehityskeskustelu - Development discussion",
  21: "Avantoiuinti - Ice swimming",
  22: "Työmatka huomenna - Work trip tomorrow",
  23: "Ruotsissa - In Sweden",
  24: "Kuntosalilla - At the gym",
  25: "Treffit - A date",
  26: "Kevät saapuu - Spring arrives",
  27: "Päivä toimistolla - A day at the office"
};
