export const quizQuestions = [
  { fi: "Kirvellä", answer: "To sting / burn", options: ["To sting / burn", "To swell", "To heal"] },
  { fi: "Särkeä", answer: "To ache", options: ["To ache", "To sneeze", "To bleed"] },
  { fi: "Väsynyt", answer: "Tired", options: ["Tired", "Hungry", "Busy"] },
  { fi: "Palella", answer: "To feel cold", options: ["To feel cold", "To sweat", "To cough"] },
  { fi: "Vuotaa", answer: "To run / leak", options: ["To run / leak", "To freeze", "To clear up"] },
  { fi: "Otsa", answer: "Forehead", options: ["Forehead", "Shoulder", "Cheek"] },
  { fi: "Levätä", answer: "To rest", options: ["To rest", "To exercise", "To hurry"] },
  { fi: "Lääkäri", answer: "Doctor", options: ["Doctor", "Pharmacist", "Dentist"] },
  { fi: "Lääkärintodistus", answer: "Doctor's certificate", options: ["Doctor's certificate", "Prescription", "Insurance card"] },
  { fi: "Sairausloma", answer: "Sick leave", options: ["Sick leave", "Annual leave", "Lunch break"] },
  { fi: "Lääkäriasema", answer: "Medical clinic / doctor's office", options: ["Medical clinic / doctor's office", "Laboratory", "Emergency vehicle"] },
  { fi: "Ajan saada", answer: "To get an appointment", options: ["To get an appointment", "To miss the bus", "To take a break"] },
  { fi: "Työterveyshuolto", answer: "Occupational health care", options: ["Occupational health care", "Public transport", "Child care"] },
  { fi: "Joutua odottamaan", answer: "To have to wait", options: ["To have to wait", "To be allowed in", "To leave early"] },
  { fi: "Ilmoittautua", answer: "To check in / register", options: ["To check in / register", "To complain", "To subscribe"] },
  { fi: "Tiski", answer: "Desk / counter", options: ["Desk / counter", "Shelf", "Hallway"] },
  { fi: "Keuhkot", answer: "Lungs", options: ["Lungs", "Ears", "Knees"] },
  { fi: "Puutikku", answer: "Wooden stick / tongue depressor", options: ["Wooden stick / tongue depressor", "Bandage", "Thermometer"] },
  { fi: "Kieli", answer: "Tongue", options: ["Tongue", "Jaw", "Neck"] },
  { fi: "Oksentaa", answer: "To vomit", options: ["To vomit", "To faint", "To recover"] },
  { fi: "Kuume", answer: "Fever", options: ["Fever", "Rash", "Sprain"] },
  { fi: "Kyseessä on", answer: "It is / the matter is", options: ["It is / the matter is", "It depends", "It used to be"] },
  { fi: "Tavallinen", answer: "Ordinary / common", options: ["Ordinary / common", "Severe", "Rare"] },
  { fi: "Flunssa", answer: "Flu / cold", options: ["Flu / cold", "Allergy", "Head injury"] },
  { fi: "Arvata", answer: "To guess", options: ["To guess", "To prescribe", "To examine"] },
  { fi: "Kahdeksi päiväksi", answer: "For two days", options: ["For two days", "Twice a day", "In two weeks"] },
  { fi: "Särkylääke", answer: "Pain medicine", options: ["Pain medicine", "Cough syrup", "Vitamin tablet"] },
  { fi: "Kunnolla", answer: "Properly / thoroughly", options: ["Properly / thoroughly", "Quietly", "Immediately"] },
  { fi: "Neste", answer: "Liquid / fluid", options: ["Liquid / fluid", "Porridge", "Steam"] },
  { fi: "Nyökätä", answer: "To nod", options: ["To nod", "To shrug", "To wave"] },
  { fi: "Neuvo", answer: "Advice", options: ["Advice", "Warning sign", "Symptom"] },
  { fi: "Äitinsä", answer: "His/her mother", options: ["His/her mother", "His/her aunt", "His/her doctor"] },
];
