export const quizQuestions = [
  { fi: "zhzhet - жжёт", answer: "To sting / burn", options: ["To sting / burn", "To swell", "To heal"] },
  { fi: "bolet - болеть", answer: "To ache", options: ["To ache", "To sneeze", "To bleed"] },
  { fi: "ustalyy - усталый", answer: "Tired", options: ["Tired", "Hungry", "Busy"] },
  { fi: "myorznut - мёрзнуть", answer: "To feel cold", options: ["To feel cold", "To sweat", "To cough"] },
  { fi: "tech - течь", answer: "To run / leak", options: ["To run / leak", "To freeze", "To clear up"] },
  { fi: "lob - лоб", answer: "Forehead", options: ["Forehead", "Shoulder", "Cheek"] },
  { fi: "otdykhat - отдыхать", answer: "To rest", options: ["To rest", "To exercise", "To hurry"] },
  { fi: "vrach - врач", answer: "Doctor", options: ["Doctor", "Pharmacist", "Dentist"] },
  { fi: "spravka ot vracha - справка от врача", answer: "Doctor's certificate", options: ["Doctor's certificate", "Prescription", "Insurance card"] },
  { fi: "bolnichnyy otpusk - больничный отпуск", answer: "Sick leave", options: ["Sick leave", "Annual leave", "Lunch break"] },
  { fi: "poliklinika - поликлиника", answer: "Medical clinic / doctor's office", options: ["Medical clinic / doctor's office", "Laboratory", "Emergency vehicle"] },
  { fi: "poluchit vremya - получить время", answer: "To get an appointment", options: ["To get an appointment", "To miss the bus", "To take a break"] },
  { fi: "rabochaya meditsinskaya pomoshch - рабочая медицинская помощь", answer: "Occupational health care", options: ["Occupational health care", "Public transport", "Child care"] },
  { fi: "prikhoditsya zhdat - приходится ждать", answer: "To have to wait", options: ["To have to wait", "To be allowed in", "To leave early"] },
  { fi: "registrirovat'sya - регистрироваться", answer: "To check in / register", options: ["To check in / register", "To complain", "To subscribe"] },
  { fi: "stoyka - стойка", answer: "Desk / counter", options: ["Desk / counter", "Shelf", "Hallway"] },
  { fi: "lyogkie - лёгкие", answer: "Lungs", options: ["Lungs", "Ears", "Knees"] },
  { fi: "derevyannaya palochka - деревянная палочка", answer: "Wooden stick / tongue depressor", options: ["Wooden stick / tongue depressor", "Bandage", "Thermometer"] },
  { fi: "yazyk - язык", answer: "Tongue", options: ["Tongue", "Jaw", "Neck"] },
  { fi: "rvat - рвать", answer: "To vomit", options: ["To vomit", "To faint", "To recover"] },
  { fi: "temperatura - температура", answer: "Fever", options: ["Fever", "Rash", "Sprain"] },
  { fi: "rech o - речь о", answer: "It is / the matter is", options: ["It is / the matter is", "It depends", "It used to be"] },
  { fi: "obychnyy - обычный", answer: "Ordinary / common", options: ["Ordinary / common", "Severe", "Rare"] },
  { fi: "prostuda - простуда", answer: "Flu / cold", options: ["Flu / cold", "Allergy", "Head injury"] },
  { fi: "ugadat - угадать", answer: "To guess", options: ["To guess", "To prescribe", "To examine"] },
  { fi: "na dva dni - на два дни", answer: "For two days", options: ["For two days", "Twice a day", "In two weeks"] },
  { fi: "obezbolivayushchee lekarstvo - обезболивающее лекарство", answer: "Pain medicine", options: ["Pain medicine", "Cough syrup", "Vitamin tablet"] },
  { fi: "kak sleduet - как следует", answer: "Properly / thoroughly", options: ["Properly / thoroughly", "Quietly", "Immediately"] },
  { fi: "zhidkost - жидкость", answer: "Liquid / fluid", options: ["Liquid / fluid", "Porridge", "Steam"] },
  { fi: "kivnut - кивнуть", answer: "To nod", options: ["To nod", "To shrug", "To wave"] },
  { fi: "sovet - совет", answer: "Advice", options: ["Advice", "Warning sign", "Symptom"] },
  { fi: "ego mat - его мать", answer: "His/her mother", options: ["His/her mother", "His/her aunt", "His/her doctor"] },
];
