export const quizQuestions = [
  { fi: "Silittää", answer: "To iron", options: ["To iron", "To wash", "To fold"] },
  { fi: "Työmatka", answer: "Work trip", options: ["Work trip", "Holiday trip", "Commute by bus"] },
  { fi: "Asiakas", answer: "Client / customer", options: ["Client / customer", "Manager", "Colleague"] },
  { fi: "Sileä", answer: "Smooth", options: ["Smooth", "Dirty", "Wet"] },
  { fi: "Ryppy", answer: "Wrinkle", options: ["Wrinkle", "Button", "Seam"] },
  { fi: "Lentolippu", answer: "Flight ticket", options: ["Flight ticket", "Passport", "Boarding gate"] },
  { fi: "Lentokenttä", answer: "Airport", options: ["Airport", "Train station", "Harbor"] },
  { fi: "Taaksepäin", answer: "Backward", options: ["Backward", "Forward", "Sideways"] },
  { fi: "Passintarkastus", answer: "Passport control", options: ["Passport control", "Security check", "Customs declaration"] },
  { fi: "Matkalaukku", answer: "Suitcase", options: ["Suitcase", "Backpack", "Handbag"] },
  { fi: "Käsimatkatavarat", answer: "Hand luggage", options: ["Hand luggage", "Checked baggage", "Travel documents"] },
  { fi: "Raitiovaunu", answer: "Tram", options: ["Tram", "Metro", "Taxi"] },
  { fi: "Asema", answer: "Station", options: ["Station", "Office", "Platform"] },
  { fi: "Kilometri", answer: "Kilometer", options: ["Kilometer", "Mile", "Meter"] },
  { fi: "Varttia yli", answer: "Quarter past", options: ["Quarter past", "Quarter to", "Half past"] },
  { fi: "Herätys", answer: "Wake-up / alarm", options: ["Wake-up / alarm", "Nap", "Bedtime"] },
  { fi: "Pakkaa", answer: "Packs", options: ["Packs", "Opens", "Drops"] },
  { fi: "Partavesi", answer: "Aftershave", options: ["Aftershave", "Perfume", "Shampoo"] },
  { fi: "Hammasharja", answer: "Toothbrush", options: ["Toothbrush", "Toothpaste", "Comb"] },
  { fi: "Laturi", answer: "Charger", options: ["Charger", "Battery", "Adapter"] },
  { fi: "Varmuuden vuoksi", answer: "Just in case", options: ["Just in case", "At least", "As usual"] },
  { fi: "Kolmas", answer: "Third", options: ["Third", "Second", "Last"] },
  { fi: "Makaamaan", answer: "To lie down", options: ["To lie down", "To sit down", "To stand up"] },
  { fi: "Sulkea", answer: "To close", options: ["To close", "To open", "To lock"] },
  { fi: "Ääneen", answer: "Out loud", options: ["Out loud", "Quietly", "In writing"] },
  { fi: "Nukahtaa", answer: "To fall asleep", options: ["To fall asleep", "To wake up", "To dream"] },
  { fi: "Huokaa", answer: "Sighs", options: ["Sighs", "Laughs", "Whispers"] },
  { fi: "Tarkistamassa", answer: "Checking", options: ["Checking", "Cleaning", "Carrying"] },
  { fi: "Mukana", answer: "Included / with", options: ["Included / with", "Missing", "Broken"] },
  { fi: "Takaisin", answer: "Back", options: ["Back", "Away", "Nearby"] },
  { fi: "Kuudelta", answer: "At six", options: ["At six", "At seven", "At five"] },
  { fi: "Yksitoista", answer: "Eleven", options: ["Eleven", "Ten", "Twelve"] },
];
