export const quizQuestions = [
  { fi: "Jääkylmä", answer: "Freezing cold", options: ["Freezing cold", "Boiling hot", "Windy"] },
  { fi: "Aurinko paistaa", answer: "The sun is shining", options: ["The sun is shining", "It is raining", "It is snowing"] },
  { fi: "Läpi", answer: "Through", options: ["Through", "Around", "Above"] },
  { fi: "Poissa", answer: "Gone / away", options: ["Gone / away", "Near", "Open"] },
  { fi: "Nurmikko", answer: "Lawn", options: ["Lawn", "Bridge", "Street"] },
  { fi: "Esittää", answer: "To perform / present", options: ["To perform / present", "To buy", "To carry"] },
  { fi: "Lahjoittaa", answer: "To donate", options: ["To donate", "To borrow", "To hide"] },
  { fi: "Mobiilimaksu", answer: "Mobile payment", options: ["Mobile payment", "Cash register", "Train ticket"] },
  { fi: "Nokka", answer: "Beak", options: ["Beak", "Wing", "Tail"] },
  { fi: "Kärry", answer: "Cart", options: ["Cart", "Bag", "Shelf"] },
  { fi: "Taapero", answer: "Toddler", options: ["Toddler", "Teenager", "Grandparent"] },
  { fi: "Osoittaa", answer: "To point", options: ["To point", "To throw", "To sing"] },
  { fi: "Jäätelömyyjä", answer: "Ice cream seller", options: ["Ice cream seller", "Fish seller", "Taxi driver"] },
  { fi: "Ilmaiseksi", answer: "For free", options: ["For free", "With discount", "Expensively"] },
  { fi: "Kyyneleet", answer: "Tears", options: ["Tears", "Sweat", "Drops"] },
  { fi: "Kevätaurinko", answer: "Spring sun", options: ["Spring sun", "Winter storm", "Autumn wind"] },
  { fi: "Nurkassa", answer: "In the corner", options: ["In the corner", "On the roof", "By the sea"] },
  { fi: "Riisua", answer: "To take off (clothes)", options: ["To take off (clothes)", "To put on", "To wash"] },
  { fi: "Kauppatori", answer: "Market Square", options: ["Market Square", "Railway station", "City hall"] },
  { fi: "Myyjä", answer: "Seller / vendor", options: ["Seller / vendor", "Visitor", "Teacher"] },
  { fi: "Muikku", answer: "Vendace", options: ["Vendace", "Salmon", "Trout"] },
  { fi: "Tuore", answer: "Fresh", options: ["Fresh", "Frozen", "Dry"] },
  { fi: "Turisti", answer: "Tourist", options: ["Tourist", "Local", "Neighbor"] },
  { fi: "Lautta", answer: "Ferry", options: ["Ferry", "Tram", "Airplane"] },
  { fi: "Kulkea", answer: "To go / run (route)", options: ["To go / run (route)", "To stop", "To disappear"] },
  { fi: "Jatkaa", answer: "To continue", options: ["To continue", "To cancel", "To wait"] },
  { fi: "Vuokra-asunto", answer: "Rental apartment", options: ["Rental apartment", "Office building", "Hotel room"] },
  { fi: "Muovilta", answer: "Like plastic / from plastic", options: ["Like plastic / from plastic", "Like wood", "Like perfume"] },
  { fi: "Kylpyhuone", answer: "Bathroom", options: ["Bathroom", "Kitchen", "Hallway"] },
  { fi: "Koputtaa", answer: "To knock", options: ["To knock", "To lock", "To open"] },
  { fi: "Auki", answer: "Open", options: ["Open", "Closed", "Broken"] },
  { fi: "Katsomaan", answer: "To look/check", options: ["To look/check", "To repair", "To paint"] },
  { fi: "Muuttaa takaisin", answer: "To move back", options: ["To move back", "To move out forever", "To stay away"] },
  { fi: "Hetken", answer: "For a moment", options: ["For a moment", "For an hour", "For a week"] },
  { fi: "Kiiltävä", answer: "Shiny", options: ["Shiny", "Dirty", "Heavy"] },
  { fi: "Keskustaan", answer: "To downtown / city center", options: ["To downtown / city center", "To the suburbs", "To the airport"] },
  { fi: "Yhdessä", answer: "Together", options: ["Together", "Separately", "Silently"] },
];
