export const quizQuestions = [
  { fi: "Asentaa", answer: "To install", options: ["To install", "To delete", "To repair"] },
  { fi: "Deittisovellus", answer: "Dating app", options: ["Dating app", "Calendar app", "Taxi app"] },
  { fi: "Profiili", answer: "Profile", options: ["Profile", "Password", "Message"] },
  { fi: "Puoliksi", answer: "Half / partly", options: ["Half / partly", "Completely", "Barely"] },
  { fi: "Ohjelmointi", answer: "Programming", options: ["Programming", "Design", "Accounting"] },
  { fi: "Harrastukset", answer: "Hobbies", options: ["Hobbies", "Worries", "Rules"] },
  { fi: "Viesti", answer: "Message", options: ["Message", "Photo", "Appointment"] },
  { fi: "Kirjoittaa", answer: "To write", options: ["To write", "To call", "To read"] },
  { fi: "Yhdelle", answer: "To one person", options: ["To one person", "To everyone", "To no one"] },
  { fi: "Yrittää", answer: "To try", options: ["To try", "To avoid", "To forget"] },
  { fi: "Tapaaminen", answer: "Meeting", options: ["Meeting", "Dinner", "Trip"] },
  { fi: "Ylihuomenna", answer: "The day after tomorrow", options: ["The day after tomorrow", "Tomorrow", "Yesterday"] },
  { fi: "Pyykkipäivä", answer: "Laundry day", options: ["Laundry day", "Payday", "Holiday"] },
  { fi: "Treffit", answer: "Date (romantic)", options: ["Date (romantic)", "Exercise", "Lunch break"] },
  { fi: "Saapua", answer: "To arrive", options: ["To arrive", "To leave", "To wait"] },
  { fi: "Kahvila", answer: "Cafe", options: ["Cafe", "Office", "Library"] },
  { fi: "Tervehtiä", answer: "To greet", options: ["To greet", "To argue", "To interrupt"] },
  { fi: "Tilata", answer: "To order", options: ["To order", "To clean", "To borrow"] },
  { fi: "Kodikas", answer: "Cozy", options: ["Cozy", "Noisy", "Crowded"] },
  { fi: "Tapetti", answer: "Wallpaper", options: ["Wallpaper", "Tablecloth", "Poster"] },
  { fi: "Mustavalkoinen", answer: "Black-and-white", options: ["Black-and-white", "Colorful", "Transparent"] },
  { fi: "Hiljaista", answer: "Quiet", options: ["Quiet", "Busy", "Late"] },
  { fi: "Hymyillä", answer: "To smile", options: ["To smile", "To shout", "To sneeze"] },
  { fi: "Kalenteri", answer: "Calendar", options: ["Calendar", "Notebook", "Map"] },
  { fi: "Uudestaan", answer: "Again", options: ["Again", "Never", "Sooner"] },
  { fi: "Viikon päästä", answer: "In a week", options: ["In a week", "Last week", "Every week"] },
  { fi: "Tarkemmin", answer: "More carefully", options: ["More carefully", "More loudly", "More quickly"] },
  { fi: "Taloyhtiö", answer: "Housing company", options: ["Housing company", "Sports club", "Bank branch"] },
  { fi: "Kokous", answer: "Meeting", options: ["Meeting", "Vacation", "Invoice"] },
  { fi: "Selata", answer: "To scroll / browse", options: ["To scroll / browse", "To print", "To lock"] },
  { fi: "Miettiä", answer: "To think", options: ["To think", "To sleep", "To dance"] },
  { fi: "Myöhemmin", answer: "Later", options: ["Later", "Immediately", "Earlier"] },
  { fi: "Kätellä", answer: "To shake hands", options: ["To shake hands", "To hug", "To wave"] },
  { fi: "Suuntiin", answer: "Directions", options: ["Directions", "Messages", "Seats"] },
];
