export const quizQuestions = [
  { fi: "budilnik - будильник", answer: "Alarm clock", options: ["Alarm clock", "Seat belt", "Traffic light"] },
  { fi: "vyezzhat - выезжать", answer: "Leaving / on the way out", options: ["Leaving / on the way out", "Sleeping in", "Waiting outside"] },
  { fi: "dannye internet-banka - данные интернет-банка", answer: "Online banking credentials", options: ["Online banking credentials", "Train tickets", "Insurance papers"] },
  { fi: "poobeshchat - пообещать", answer: "Promised", options: ["Promised", "Forgotten", "Recommended"] },
  { fi: "zabrat na mashine - забрать на машине", answer: "To pick someone up by car", options: ["To pick someone up by car", "To wash the car", "To rent a car"] },
  { fi: "prosypat'sya - просыпаться", answer: "Waking up", options: ["Waking up", "Closing down", "Getting lost"] },
  { fi: "vygulivat - выгуливать", answer: "To walk (a dog) / take outside", options: ["To walk (a dog) / take outside", "To feed", "To train"] },
  { fi: "avtodoroga - автодорога", answer: "Motorway / highway", options: ["Motorway / highway", "Country road", "Pedestrian street"] },
  { fi: "skorostnoy limit - скоростной лимит", answer: "Speed limit", options: ["Speed limit", "Parking permit", "Fuel gauge"] },
  { fi: "kasha - каша", answer: "Slush", options: ["Slush", "Fog", "Gravel"] },
  { fi: "koleso - колесо", answer: "Tire", options: ["Tire", "Mirror", "Headlight"] },
  { fi: "dnishche - днище", answer: "Bottom / underside", options: ["Bottom / underside", "Roof", "Handle"] },
  { fi: "tormozit - тормозить", answer: "To brake", options: ["To brake", "To accelerate", "To reverse"] },
  { fi: "bezopasnost - безопасность", answer: "Safety", options: ["Safety", "Silence", "Convenience"] },
  { fi: "zapravka - заправка", answer: "Service station / gas station", options: ["Service station / gas station", "Repair garage", "Car wash"] },
  { fi: "s soboy - с собой", answer: "To go / take along, takeaway", options: ["To go / take along, takeaway", "At home only", "For later pickup"] },
  { fi: "parit - парить", answer: "To steam", options: ["To steam", "To freeze", "To spill"] },
  { fi: "zhit komfortno - жить комфортно", answer: "To enjoy oneself / like being somewhere", options: ["To enjoy oneself / like being somewhere", "To get tired", "To get worried"] },
  { fi: "lyubit chto-to - любить что-то", answer: "To like something", options: ["To like something", "To search for something", "To repair something"] },
  { fi: "skuchat - скучать", answer: "To miss / long for", options: ["To miss / long for", "To avoid", "To save"] },
  { fi: "peyzazh - пейзаж", answer: "Landscape / scenery", options: ["Landscape / scenery", "Weather forecast", "Traffic sign"] },
  { fi: "vverkh - вверх", answer: "Uphill", options: ["Uphill", "Crosswalk", "Intersection"] },
  { fi: "vniz - вниз", answer: "Downhill", options: ["Downhill", "Driveway", "Bus lane"] },
  { fi: "pole - поле", answer: "Field", options: ["Field", "Forest", "Bridge"] },
  { fi: "ambar - амбар", answer: "Barn", options: ["Barn", "Garage", "Tower"] },
  { fi: "tikho - тихо", answer: "Quiet", options: ["Quiet", "Expensive", "Crowded"] },
  { fi: "klient - клиент", answer: "Customer", options: ["Customer", "Driver", "Patient"] },
  { fi: "ocherednoy nomer - очередной номер", answer: "Queue number / turn number", options: ["Queue number / turn number", "Password", "License plate"] },
  { fi: "pozvat k sebe - позвать к себе", answer: "To call someone over", options: ["To call someone over", "To send away", "To write down"] },
  { fi: "ustanovit - установить", answer: "To install", options: ["To install", "To compare", "To unlock"] },
  { fi: "prilozhenie - приложение", answer: "App / application", options: ["App / application", "Receipt", "Keyboard"] },
  { fi: "gotovo - готово", answer: "Ready", options: ["Ready", "Broken", "Delayed"] },
  { fi: "avtorizovat'sya - авторизоваться", answer: "To identify oneself / authenticate", options: ["To identify oneself / authenticate", "To subscribe", "To forward"] },
  { fi: "kafedra - кафедра", answer: "Cathedral", options: ["Cathedral", "Town hall", "Library"] },
  { fi: "laryok - ларёк", answer: "Cart", options: ["Cart", "Bench", "Lantern"] },
  { fi: "napitok - напиток", answer: "Drink / beverage", options: ["Drink / beverage", "Snack", "Medicine"] },
  { fi: "glyog - глёг", answer: "Mulled drink / glogi", options: ["Mulled drink / glogi", "Ice tea", "Mineral water"] },
  { fi: "oblegchennyy - облегченный", answer: "Relieved", options: ["Relieved", "Ashamed", "Annoyed"] },
  { fi: "bereg - берег", answer: "Shore", options: ["Shore", "Tunnel", "Balcony"] },
  { fi: "techt - течь", answer: "To flow", options: ["To flow", "To sink", "To reflect"] },
  { fi: "lyd-floe - лёд-флое", answer: "Ice floe", options: ["Ice floe", "Snowbank", "Puddle"] },
  { fi: "glotok - глоток", answer: "Sip / gulp", options: ["Sip / gulp", "Bite", "Smell"] },
  { fi: "ruchnoy tormoz - ручной тормоз", answer: "Handbrake", options: ["Handbrake", "Seat heater", "Gear stick"] },
  { fi: "vetrosteklo - ветростекло", answer: "Windshield", options: ["Windshield", "Rear wheel", "Exhaust pipe"] },
  { fi: "dvornik - дворник", answer: "Wiper", options: ["Wiper", "Seat cover", "Fuel cap"] },
];
