export const quizQuestions = [
  { fi: "Herätyskello", answer: "Alarm clock", options: ["Alarm clock", "Seat belt", "Traffic light"] },
  { fi: "Lähdössä", answer: "Leaving / on the way out", options: ["Leaving / on the way out", "Sleeping in", "Waiting outside"] },
  { fi: "Verkkopankkitunnukset", answer: "Online banking credentials", options: ["Online banking credentials", "Train tickets", "Insurance papers"] },
  { fi: "Luvannut", answer: "Promised", options: ["Promised", "Forgotten", "Recommended"] },
  { fi: "Hakea autolla", answer: "To pick someone up by car", options: ["To pick someone up by car", "To wash the car", "To rent a car"] },
  { fi: "Heräämässä", answer: "Waking up", options: ["Waking up", "Closing down", "Getting lost"] },
  { fi: "Ulkoiluttaa", answer: "To walk (a dog) / take outside", options: ["To walk (a dog) / take outside", "To feed", "To train"] },
  { fi: "Moottoritie", answer: "Motorway / highway", options: ["Motorway / highway", "Country road", "Pedestrian street"] },
  { fi: "Nopeusrajoitus", answer: "Speed limit", options: ["Speed limit", "Parking permit", "Fuel gauge"] },
  { fi: "Loska", answer: "Slush", options: ["Slush", "Fog", "Gravel"] },
  { fi: "Rengas", answer: "Tire", options: ["Tire", "Mirror", "Headlight"] },
  { fi: "Pohja", answer: "Bottom / underside", options: ["Bottom / underside", "Roof", "Handle"] },
  { fi: "Jarruttaa", answer: "To brake", options: ["To brake", "To accelerate", "To reverse"] },
  { fi: "Turvallisuus", answer: "Safety", options: ["Safety", "Silence", "Convenience"] },
  { fi: "Huoltoasema", answer: "Service station / gas station", options: ["Service station / gas station", "Repair garage", "Car wash"] },
  { fi: "Mukaan", answer: "To go / take along, takeaway", options: ["To go / take along, takeaway", "At home only", "For later pickup"] },
  { fi: "Höyrytä", answer: "To steam", options: ["To steam", "To freeze", "To spill"] },
  { fi: "Viihtyä", answer: "To enjoy oneself / like being somewhere", options: ["To enjoy oneself / like being somewhere", "To get tired", "To get worried"] },
  { fi: "Pitää jostakin", answer: "To like something", options: ["To like something", "To search for something", "To repair something"] },
  { fi: "Kaivata", answer: "To miss / long for", options: ["To miss / long for", "To avoid", "To save"] },
  { fi: "Maisema", answer: "Landscape / scenery", options: ["Landscape / scenery", "Weather forecast", "Traffic sign"] },
  { fi: "Ylämäki", answer: "Uphill", options: ["Uphill", "Crosswalk", "Intersection"] },
  { fi: "Alamäki", answer: "Downhill", options: ["Downhill", "Driveway", "Bus lane"] },
  { fi: "Pelto", answer: "Field", options: ["Field", "Forest", "Bridge"] },
  { fi: "Lato", answer: "Barn", options: ["Barn", "Garage", "Tower"] },
  { fi: "Hiljaista", answer: "Quiet", options: ["Quiet", "Expensive", "Crowded"] },
  { fi: "Asiakas", answer: "Customer", options: ["Customer", "Driver", "Patient"] },
  { fi: "Vuoronumero", answer: "Queue number / turn number", options: ["Queue number / turn number", "Password", "License plate"] },
  { fi: "Kutsua luokseen", answer: "To call someone over", options: ["To call someone over", "To send away", "To write down"] },
  { fi: "Asentaa", answer: "To install", options: ["To install", "To compare", "To unlock"] },
  { fi: "Sovellus", answer: "App / application", options: ["App / application", "Receipt", "Keyboard"] },
  { fi: "Valmista", answer: "Ready", options: ["Ready", "Broken", "Delayed"] },
  { fi: "Tunnistautua", answer: "To identify oneself / authenticate", options: ["To identify oneself / authenticate", "To subscribe", "To forward"] },
  { fi: "Tuomiokirkko", answer: "Cathedral", options: ["Cathedral", "Town hall", "Library"] },
  { fi: "Kärry", answer: "Cart", options: ["Cart", "Bench", "Lantern"] },
  { fi: "Juoma", answer: "Drink / beverage", options: ["Drink / beverage", "Snack", "Medicine"] },
  { fi: "Glögi", answer: "Mulled drink / glogi", options: ["Mulled drink / glogi", "Ice tea", "Mineral water"] },
  { fi: "Helpottunut", answer: "Relieved", options: ["Relieved", "Ashamed", "Annoyed"] },
  { fi: "Ranta", answer: "Shore", options: ["Shore", "Tunnel", "Balcony"] },
  { fi: "Virrata", answer: "To flow", options: ["To flow", "To sink", "To reflect"] },
  { fi: "Jäälautta", answer: "Ice floe", options: ["Ice floe", "Snowbank", "Puddle"] },
  { fi: "Kulaus", answer: "Sip / gulp", options: ["Sip / gulp", "Bite", "Smell"] },
  { fi: "Käsijarru", answer: "Handbrake", options: ["Handbrake", "Seat heater", "Gear stick"] },
  { fi: "Tuulilasi", answer: "Windshield", options: ["Windshield", "Rear wheel", "Exhaust pipe"] },
  { fi: "Pyyhin", answer: "Wiper", options: ["Wiper", "Seat cover", "Fuel cap"] },
];
