export const quizQuestions = [
  { fi: "Sunnuntaiaamuna", answer: "On Sunday morning", options: ["On Sunday morning", "On Monday evening", "At midnight"] },
  { fi: "Nojata", answer: "To lean (against)", options: ["To lean (against)", "To jump over", "To paint"] },
  { fi: "Työryhmä", answer: "Work group / team", options: ["Work group / team", "Family chat", "Sports club"] },
  { fi: "Lainata", answer: "To borrow", options: ["To borrow", "To sell", "To repair"] },
  { fi: "Paloheinä", answer: "Paloheinä (area in Helsinki)", options: ["Paloheinä (area in Helsinki)", "A ski brand", "A mountain range"] },
  { fi: "Toiseksi korkein", answer: "Second highest", options: ["Second highest", "Most crowded", "Least expensive"] },
  { fi: "Parkkipaikka", answer: "Parking lot", options: ["Parking lot", "Bus lane", "Ticket office"] },
  { fi: "Hiihtänyt", answer: "Skied (past participle)", options: ["Skied (past participle)", "Driven", "Climbed"] },
  { fi: "Potku", answer: "Push / kick", options: ["Push / kick", "Turn signal", "Braking point"] },
  { fi: "Liuku", answer: "Glide", options: ["Glide", "Shortcut", "Checkpoint"] },
  { fi: "Kaatua", answer: "To fall down", options: ["To fall down", "To overtake", "To stretch"] },
  { fi: "Auttaa ylös", answer: "To help up", options: ["To help up", "To push away", "To check in"] },
  { fi: "Ravistaa", answer: "To shake", options: ["To shake", "To tie", "To postpone"] },
  { fi: "Takiltaan", answer: "From his/her jacket", options: ["From his/her jacket", "Into the backpack", "Over the boots"] },
  { fi: "Tielle", answer: "Into the way / path", options: ["Into the way / path", "Under the bridge", "Behind the bench"] },
  { fi: "Horjahtaa", answer: "To stumble / wobble", options: ["To stumble / wobble", "To sprint", "To whistle"] },
  { fi: "Hiihdolta", answer: "Like skiing / as skiing", options: ["Like skiing / as skiing", "Without skiing", "Before skiing"] },
  { fi: "Metsän läpi", answer: "Through the forest", options: ["Through the forest", "Around the lake", "Across the bridge"] },
  { fi: "Oksilla", answer: "On the branches", options: ["On the branches", "Under the roof", "Inside the tunnel"] },
  { fi: "Välistä", answer: "From between / through", options: ["From between / through", "From above", "From below"] },
  { fi: "Laduilla", answer: "On the ski tracks", options: ["On the ski tracks", "At the ski shop", "Near the station"] },
  { fi: "Osua", answer: "To hit / bump into", options: ["To hit / bump into", "To wave at", "To wait for"] },
  { fi: "Pysähtyä", answer: "To stop", options: ["To stop", "To descend", "To accelerate"] },
  { fi: "Pysytään oikealla", answer: "Stay on the right", options: ["Stay on the right", "Turn around now", "Wait at the left"] },
  { fi: "Kierros", answer: "Lap / round", options: ["Lap / round", "Ticket", "Entrance"] },
  { fi: "Hikinen", answer: "Sweaty", options: ["Sweaty", "Exhausted", "Silent"] },
  { fi: "Lyhyt matka", answer: "Short distance", options: ["Short distance", "Steep slope", "Long break"] },
  { fi: "Kaakao", answer: "Cocoa / hot chocolate", options: ["Cocoa / hot chocolate", "Espresso", "Smoothie"] },
  { fi: "Kylmetä", answer: "To get colder", options: ["To get colder", "To get calmer", "To get sunnier"] },
  { fi: "Lähteä kotiin", answer: "To head home", options: ["To head home", "To check in", "To change trains"] },
];

