export const quizQuestions = [
  { fi: "voskresnym utrom - воскресным утром", answer: "On Sunday morning", options: ["On Sunday morning", "On Monday evening", "At midnight"] },
  { fi: "prislonyat - прислонять", answer: "To lean (against)", options: ["To lean (against)", "To jump over", "To paint"] },
  { fi: "rabochaya gruppa - рабочая группа", answer: "Work group / team", options: ["Work group / team", "Family chat", "Sports club"] },
  { fi: "brat - брать", answer: "To borrow", options: ["To borrow", "To sell", "To repair"] },
  { fi: "Paloheinya - Палохейня", answer: "Paloheinä (area in Helsinki)", options: ["Paloheinä (area in Helsinki)", "A ski brand", "A mountain range"] },
  { fi: "vtoroy po vysote - второй по высоте", answer: "Second highest", options: ["Second highest", "Most crowded", "Least expensive"] },
  { fi: "parkovka - парковка", answer: "Parking lot", options: ["Parking lot", "Bus lane", "Ticket office"] },
  { fi: "katalsya - катался", answer: "Skied (past participle)", options: ["Skied (past participle)", "Driven", "Climbed"] },
  { fi: "tolchok - толчок", answer: "Push / kick", options: ["Push / kick", "Turn signal", "Braking point"] },
  { fi: "skolzhenie - скольжение", answer: "Glide", options: ["Glide", "Shortcut", "Checkpoint"] },
  { fi: "padat - падать", answer: "To fall down", options: ["To fall down", "To overtake", "To stretch"] },
  { fi: "pomoch vstat - помочь встать", answer: "To help up", options: ["To help up", "To push away", "To check in"] },
  { fi: "otryakhat - отряхать", answer: "To shake", options: ["To shake", "To tie", "To postpone"] },
  { fi: "s kurtki - с куртки", answer: "From his/her jacket", options: ["From his/her jacket", "Into the backpack", "Over the boots"] },
  { fi: "na put - на путь", answer: "Into the way / path", options: ["Into the way / path", "Under the bridge", "Behind the bench"] },
  { fi: "shatat'sya - шататься", answer: "To stumble / wobble", options: ["To stumble / wobble", "To sprint", "To whistle"] },
  { fi: "pokhozhe na katanie - похоже на катание", answer: "Like skiing / as skiing", options: ["Like skiing / as skiing", "Without skiing", "Before skiing"] },
  { fi: "cherez les - через лес", answer: "Through the forest", options: ["Through the forest", "Around the lake", "Across the bridge"] },
  { fi: "na vetkakh - на ветках", answer: "On the branches", options: ["On the branches", "Under the roof", "Inside the tunnel"] },
  { fi: "mezhdu - между", answer: "From between / through", options: ["From between / through", "From above", "From below"] },
  { fi: "na trassakh - на трассах", answer: "On the ski tracks", options: ["On the ski tracks", "At the ski shop", "Near the station"] },
  { fi: "zadet - задеть", answer: "To hit / bump into", options: ["To hit / bump into", "To wave at", "To wait for"] },
  { fi: "ostanovit'sya - остановиться", answer: "To stop", options: ["To stop", "To descend", "To accelerate"] },
  { fi: "derzhites sprava - держитесь справа", answer: "Stay on the right", options: ["Stay on the right", "Turn around now", "Wait at the left"] },
  { fi: "krug - круг", answer: "Lap / round", options: ["Lap / round", "Ticket", "Entrance"] },
  { fi: "potnyy - потный", answer: "Sweaty", options: ["Sweaty", "Exhausted", "Silent"] },
  { fi: "korotkaya distantsiya - короткая дистанция", answer: "Short distance", options: ["Short distance", "Steep slope", "Long break"] },
  { fi: "kakao - какао", answer: "Cocoa / hot chocolate", options: ["Cocoa / hot chocolate", "Espresso", "Smoothie"] },
  { fi: "kholodat - холодать", answer: "To get colder", options: ["To get colder", "To get calmer", "To get sunnier"] },
  { fi: "idti domoy - идти домой", answer: "To head home", options: ["To head home", "To check in", "To change trains"] },
];
