export const quizQuestions = [
  { fi: "Apteekki", answer: "Pharmacy", options: ["Pharmacy", "Clinic", "Laboratory"] },
  { fi: "Valaistus", answer: "Lighting", options: ["Lighting", "Prescription", "Queue number"] },
  { fi: "Hylly", answer: "Shelf", options: ["Shelf", "Counter", "Receipt"] },
  { fi: "Pakkaus", answer: "Package / packet", options: ["Package / packet", "Bottle opener", "Mirror"] },
  { fi: "Vuoronumero", answer: "Queue number / turn number", options: ["Queue number / turn number", "Patient record", "Medicine label"] },
  { fi: "Näyttö", answer: "Display / screen", options: ["Display / screen", "Drawer", "Cabinet"] },
  { fi: "Oire", answer: "Symptom", options: ["Symptom", "Dosage", "Insurance"] },
  { fi: "Kurkkukipu", answer: "Sore throat", options: ["Sore throat", "Back pain", "Ear infection"] },
  { fi: "Päänsärky", answer: "Headache", options: ["Headache", "Dizziness", "Cough"] },
  { fi: "Farmaseutti", answer: "Pharmacist", options: ["Pharmacist", "Surgeon", "Receptionist"] },
  { fi: "Rauhallisesti", answer: "Calmly", options: ["Calmly", "Loudly", "Suddenly"] },
  { fi: "Ibuprofeeni", answer: "Ibuprofen", options: ["Ibuprofen", "Insulin", "Antibiotic"] },
  { fi: "Vahvempi", answer: "Stronger", options: ["Stronger", "Cheaper", "Safer"] },
  { fi: "Aspiriini", answer: "Aspirin", options: ["Aspirin", "Vitamin D", "Cough syrup"] },
  { fi: "Parasetamoli", answer: "Paracetamol", options: ["Paracetamol", "Antacid", "Antihistamine"] },
  { fi: "Resepti", answer: "Prescription", options: ["Prescription", "Receipt", "Coupon"] },
  { fi: "Kuumemittari", answer: "Thermometer", options: ["Thermometer", "Bandage", "Face mask"] },
  { fi: "Nenäsuihke", answer: "Nasal spray", options: ["Nasal spray", "Eye wash", "Hand cream"] },
  { fi: "Silmätipat", answer: "Eye drops", options: ["Eye drops", "Ear drops", "Cough drops"] },
  { fi: "Vitamiini", answer: "Vitamin", options: ["Vitamin", "Pain patch", "Sleeping pill"] },
  { fi: "Kassalle", answer: "To the checkout / cashier", options: ["To the checkout / cashier", "To the waiting room", "To the lab"] },
  { fi: "Jollekin toiselle", answer: "For someone else", options: ["For someone else", "For later", "For work"] },
  { fi: "Lääkkeet", answer: "Medicines", options: ["Medicines", "Glasses", "Documents"] },
  { fi: "Reppu", answer: "Backpack", options: ["Backpack", "Jacket pocket", "Medicine cabinet"] },
  { fi: "Paleleminen", answer: "Shivering / feeling cold", options: ["Shivering / feeling cold", "Sneezing", "Recovering"] },
  { fi: "Lämpö", answer: "Temperature", options: ["Temperature", "Prescription fee", "Blood pressure"] },
  { fi: "Särkylääke", answer: "Painkiller / pain medicine", options: ["Painkiller / pain medicine", "Vitamin supplement", "Cough medicine"] },
  { fi: "Takaisin", answer: "Back", options: ["Back", "Outside", "Upstairs"] },
  { fi: "Tulossa", answer: "Coming / on the way", options: ["Coming / on the way", "Cancelled", "Finished"] },
  { fi: "Harmittaa", answer: "To bother / upset", options: ["To bother / upset", "To relax", "To improve"] },
];
