export const quizQuestions = [
  { fi: "apteka - аптека", answer: "Pharmacy", options: ["Pharmacy", "Clinic", "Laboratory"] },
  { fi: "osveshchenie - освещение", answer: "Lighting", options: ["Lighting", "Prescription", "Queue number"] },
  { fi: "polka - полка", answer: "Shelf", options: ["Shelf", "Counter", "Receipt"] },
  { fi: "upakovka - упаковка", answer: "Package / packet", options: ["Package / packet", "Bottle opener", "Mirror"] },
  { fi: "ocherednoy nomer - очередной номер", answer: "Queue number / turn number", options: ["Queue number / turn number", "Patient record", "Medicine label"] },
  { fi: "ekran - экран", answer: "Display / screen", options: ["Display / screen", "Drawer", "Cabinet"] },
  { fi: "simptom - симптом", answer: "Symptom", options: ["Symptom", "Dosage", "Insurance"] },
  { fi: "bol v gorle - боль в горле", answer: "Sore throat", options: ["Sore throat", "Back pain", "Ear infection"] },
  { fi: "golovnaya bol - головная боль", answer: "Headache", options: ["Headache", "Dizziness", "Cough"] },
  { fi: "farmatsevt - фармацевт", answer: "Pharmacist", options: ["Pharmacist", "Surgeon", "Receptionist"] },
  { fi: "spokoyno - спокойно", answer: "Calmly", options: ["Calmly", "Loudly", "Suddenly"] },
  { fi: "ibuprofen - ибупрофен", answer: "Ibuprofen", options: ["Ibuprofen", "Insulin", "Antibiotic"] },
  { fi: "silnee - сильнее", answer: "Stronger", options: ["Stronger", "Cheaper", "Safer"] },
  { fi: "aspirin - аспирин", answer: "Aspirin", options: ["Aspirin", "Vitamin D", "Cough syrup"] },
  { fi: "paratsetamol - парацетамол", answer: "Paracetamol", options: ["Paracetamol", "Antacid", "Antihistamine"] },
  { fi: "retsept - рецепт", answer: "Prescription", options: ["Prescription", "Receipt", "Coupon"] },
  { fi: "termometr - термометр", answer: "Thermometer", options: ["Thermometer", "Bandage", "Face mask"] },
  { fi: "sprej dlya nosa - спрей для носа", answer: "Nasal spray", options: ["Nasal spray", "Eye wash", "Hand cream"] },
  { fi: "glaznye kapli - глазные капли", answer: "Eye drops", options: ["Eye drops", "Ear drops", "Cough drops"] },
  { fi: "vitamin - витамин", answer: "Vitamin", options: ["Vitamin", "Pain patch", "Sleeping pill"] },
  { fi: "k kasse - к кассе", answer: "To the checkout / cashier", options: ["To the checkout / cashier", "To the waiting room", "To the lab"] },
  { fi: "dlya kogo-to drugogo - для кого-то другого", answer: "For someone else", options: ["For someone else", "For later", "For work"] },
  { fi: "lekarstva - лекарства", answer: "Medicines", options: ["Medicines", "Glasses", "Documents"] },
  { fi: "ryukzak - рюкзак", answer: "Backpack", options: ["Backpack", "Jacket pocket", "Medicine cabinet"] },
  { fi: "myorznut - мёрзнуть", answer: "Shivering / feeling cold", options: ["Shivering / feeling cold", "Sneezing", "Recovering"] },
  { fi: "temperatura - температура", answer: "Temperature", options: ["Temperature", "Prescription fee", "Blood pressure"] },
  { fi: "obezbolivayushchee lekarstvo - обезболивающее лекарство", answer: "Painkiller / pain medicine", options: ["Painkiller / pain medicine", "Vitamin supplement", "Cough medicine"] },
  { fi: "obratno - обратно", answer: "Back", options: ["Back", "Outside", "Upstairs"] },
  { fi: "idet - идёт", answer: "Coming / on the way", options: ["Coming / on the way", "Cancelled", "Finished"] },
  { fi: "dosadno - досадно", answer: "To bother / upset", options: ["To bother / upset", "To relax", "To improve"] },
];
