export const quizQuestions = [
  { fi: "razgovor o razvitii - разговор о развитии", answer: "Performance/development discussion", options: ["Performance/development discussion", "Team lunch", "Job interview"] },
  { fi: "peregovornaya komnata - переговорная комната", answer: "Meeting room", options: ["Meeting room", "Storage room", "Living room"] },
  { fi: "v posledniy moment - в последний момент", answer: "At the last minute", options: ["At the last minute", "Early in the morning", "For the first time"] },
  { fi: "anketa - анкета", answer: "Form", options: ["Form", "Invoice", "Contract"] },
  { fi: "zapolnyat - заполнять", answer: "To fill in", options: ["To fill in", "To erase", "To print"] },
  { fi: "shkala - шкала", answer: "Scale", options: ["Scale", "Schedule", "Report"] },
  { fi: "pozhimat plechami - пожимать плечами", answer: "To shrug", options: ["To shrug", "To whisper", "To wave"] },
  { fi: "plechi - плечи", answer: "Shoulders", options: ["Shoulders", "Knees", "Wrists"] },
  { fi: "navyki sotrudnichestva - навыки сотрудничества", answer: "Cooperation skills", options: ["Cooperation skills", "Typing speed", "Math skills"] },
  { fi: "kachestvo raboty - качество работы", answer: "Quality of work", options: ["Quality of work", "Working hours", "Salary level"] },
  { fi: "v bolshinstve - в большинстве", answer: "Into most (sections)", options: ["Into most (sections)", "Into none", "Into all"] },
  { fi: "chetyre iz pyati - четыре из пяти", answer: "Four out of five", options: ["Four out of five", "Five out of six", "Three out of four"] },
  { fi: "iz pervogo - из первого", answer: "From the first", options: ["From the first", "Before the first", "After the first"] },
  { fi: "uluchshat - улучшать", answer: "To improve / develop", options: ["To improve / develop", "To repeat", "To postpone"] },
  { fi: "medlenno - медленно", answer: "Slowly", options: ["Slowly", "Carefully", "Silently"] },
  { fi: "so vremenem - со временем", answer: "With time / over time", options: ["With time / over time", "Immediately", "At random"] },
  { fi: "v iyule - в июле", answer: "In July", options: ["In July", "In June", "In August"] },
  { fi: "na dachu - на дачу", answer: "To the cottage", options: ["To the cottage", "To the city center", "To the office"] },
  { fi: "ego semya - его семья", answer: "His family", options: ["His family", "His colleagues", "His friends"] },
  { fi: "na rabochem meste - на рабочем месте", answer: "To/at the workplace", options: ["To/at the workplace", "At home", "At school"] },
  { fi: "uborshchik - уборщик", answer: "Cleaner / janitor", options: ["Cleaner / janitor", "Manager", "Translator"] },
  { fi: "razgovor - разговор", answer: "Discussion", options: ["Discussion", "Presentation", "Argument"] },
  { fi: "zakanchivaetsya - заканчивается", answer: "Ends", options: ["Ends", "Begins", "Continues"] },
  { fi: "prodolzhaem - продолжаем", answer: "Let's continue", options: ["Let's continue", "Let's stop", "Let's cancel"] },
  { fi: "rabochee mesto - рабочее место", answer: "Workstation", options: ["Workstation", "Hallway", "Parking lot"] },
];
