export const quizQuestions = [
  { fi: "Kehityskeskustelu", answer: "Performance/development discussion", options: ["Performance/development discussion", "Team lunch", "Job interview"] },
  { fi: "Neuvotteluhuone", answer: "Meeting room", options: ["Meeting room", "Storage room", "Living room"] },
  { fi: "Viime hetkellä", answer: "At the last minute", options: ["At the last minute", "Early in the morning", "For the first time"] },
  { fi: "Lomake", answer: "Form", options: ["Form", "Invoice", "Contract"] },
  { fi: "Täyttää", answer: "To fill in", options: ["To fill in", "To erase", "To print"] },
  { fi: "Asteikko", answer: "Scale", options: ["Scale", "Schedule", "Report"] },
  { fi: "Kohauttaa", answer: "To shrug", options: ["To shrug", "To whisper", "To wave"] },
  { fi: "Olkapäät", answer: "Shoulders", options: ["Shoulders", "Knees", "Wrists"] },
  { fi: "Yhteistyötaidot", answer: "Cooperation skills", options: ["Cooperation skills", "Typing speed", "Math skills"] },
  { fi: "Työn laatu", answer: "Quality of work", options: ["Quality of work", "Working hours", "Salary level"] },
  { fi: "Useimpiin", answer: "Into most (sections)", options: ["Into most (sections)", "Into none", "Into all"] },
  { fi: "Neljä viidestä", answer: "Four out of five", options: ["Four out of five", "Five out of six", "Three out of four"] },
  { fi: "Ensimmäisestä", answer: "From the first", options: ["From the first", "Before the first", "After the first"] },
  { fi: "Kehittää", answer: "To improve / develop", options: ["To improve / develop", "To repeat", "To postpone"] },
  { fi: "Hitaasti", answer: "Slowly", options: ["Slowly", "Carefully", "Silently"] },
  { fi: "Ajan kanssa", answer: "With time / over time", options: ["With time / over time", "Immediately", "At random"] },
  { fi: "Heinäkuussa", answer: "In July", options: ["In July", "In June", "In August"] },
  { fi: "Mökille", answer: "To the cottage", options: ["To the cottage", "To the city center", "To the office"] },
  { fi: "Perheensä", answer: "His family", options: ["His family", "His colleagues", "His friends"] },
  { fi: "Työpaikalle", answer: "To/at the workplace", options: ["To/at the workplace", "At home", "At school"] },
  { fi: "Siivooja", answer: "Cleaner / janitor", options: ["Cleaner / janitor", "Manager", "Translator"] },
  { fi: "Keskustelu", answer: "Discussion", options: ["Discussion", "Presentation", "Argument"] },
  { fi: "Päättyy", answer: "Ends", options: ["Ends", "Begins", "Continues"] },
  { fi: "Jatketaan", answer: "Let's continue", options: ["Let's continue", "Let's stop", "Let's cancel"] },
  { fi: "Työpiste", answer: "Workstation", options: ["Workstation", "Hallway", "Parking lot"] },
];
