const article2 = [
  "At first glance, it might seem that Finnish and English don’t have that much in common.",
  "You do notice quickly that some words in Finnish are almost exactly the English word with an -i at the end: paperi = paper, moottori = motor, engine, projekti = project.",
  "If you scratch the surface a little more, you notice words like sohva = sofa, pankki = bank, kuppi = cup. And further, words that are still a bit more different but still clearly similar to English if you think about it: kahvi = coffee, hattu = hat, kellari = cellar.",
  "But the next layer of words is where it gets interesting: lasi = glass, kulta = gold, kaappi = cupboard, tuoli = chair (close to stool).",
  "If you can learn to recognize these words and also the unique “ring and tone” of Finnish, it will probably help you with your Finnish learning. The Finnish words prefer “hard consonants” more than English (k rather than g, p rather than b, t rather than d). And you might notice other kinds of patterns in the examples, in what “sounds Finnish”.",
  "Below is a long list of words that are similar in Finnish and English.",
  "<b>Miscellaneous - probably ancient loans</b>",
  "airo = oar",
  "haukka = hawk",
  "kallo = skull",
  "kammio = chamber",
  "kulta = gold",
  "kuningas = king",
  "laina = loan",
  "lammas = sheep",
  "raaka = raw",
  "ranta = shore (from strand, stranded)",
  "rengas = ring / tire",
  "rikas = rich",
  "sauma = seam",
  "vaha = wax",
  "<b>Everyday Objects</b>",
  "hattu = hat",
  "sohva = sofa",
  "naula = nail",
  "ruuvi = screw",
  "pultti = bolt",
  "saha = saw",
  "kuppi = cup",
  "lasi = glass",
  "kattila = pot (close to kettle)",
  "kellari = cellar",
  "tuoli = chair (close to stool)",
  "vaunu = wagon / carriage",
  "kaappi = cupboard",
  "lamppu = lamp",
  "kortti = card",
  "passi = passport",
  "posti = post / mail",
  "pankki = bank",
  "paperi = paper",
  "<b>Transport & Machines</b>",
  "auto = car",
  "bussi = bus",
  "metro = metro",
  "taksi = taxi",
  "moottori = motor / engine",
  "traktori = tractor",
  "generaattori = generator",
  "sylinteri = cylinder",
  "pumppu = pump",
  "tankki = tank",
  "radio = radio",
  "video = video",
  "stereo = stereo",
  "kamera = camera",
  "mikrofoni = microphone",
  "<b>Business & Work</b>",
  "budjetti = budget",
  "projekti = project",
  "strategia = strategy",
  "kategoria = category",
  "identiteetti = identity",
  "diplomi = diploma",
  "firma = company (close to firm)",
  "manageri = manager",
  "brändi = brand",
  "sponsori = sponsor",
  "trendi = trend",
  "<b>Media & Pop Culture</b>",
  "disko = disco",
  "klubi = club",
  "albumi = album",
  "trilleri = thriller",
  "komedia = comedy",
  "draama = drama",
  "<b>Tech Words (Extremely Transparent)</b>",
  "internet = internet",
  "prosessori = processor",
  "printteri = printer",
  "skanneri = scanner",
  "bitti = bit",
  "pikseli = pixel",
  "koodi = code",
  "linkki = link",
  "botti = bot",
  "<b>Food & Drink</b>",
  "pizza = pizza",
  "pasta = pasta",
  "banaani = banana",
  "suklaa = chocolate",
  "viski = whisky",
  "ketsuppi = ketchup",
  "salaatti = salad",
  "kahvi = coffee",
  "kaali = cabbage (close to kale)",
  "meloni = melon",
];

export default article2;
