const article1 = [
  "Finnish does not have words like on, in, from etc. Instead of these prepositions, Finnish uses endings.",
  "For example: On the floor becomes lattialla = lattia + -lla.",
  "In this article, we’ll go through the following endings:",
  "<table><thead><tr><th><b>Ending</b></th><th><b>Primary Meaning</b></th><th>Secondary Meanings</th></tr></thead><tbody><tr><td><b>-lla / -llä</b></td><td><b>on</b></td><td>with / by means of, e.g. kynällä = by pen (kynä = pen), autolla = by car (auto = car), ownership (\"Minulla on\" = I have), at/in, e.g. asemalla = at the station (asema = station)</td></tr><tr><td><b>-ssa / -ssä</b></td><td><b>in</b></td><td></td></tr><tr><td><b>-lta / -ltä</b></td><td><b>from on</b></td><td>At X o'clock, e.g. kolmelta = at three, of as in look/smell/taste/etc of something, e.g. maistuu hyvältä = tastes good</td></tr><tr><td><b>-sta / -stä</b></td><td><b>from in</b></td><td>In X's opinion, e.g. minusta ... = in my opinion, ..., about/concerning, e.g. puhumme Suomesta = We are talking about Finland, like/interest/etc, e.g. Pidän tästä = I like this</td></tr><tr><td><b>-lle</b></td><td><b>onto</b></td><td>for someone or someone, e.g se on hänelle = it's for him/her</td></tr><tr><td><b>-in / -an / -en etc</b></td><td><b>into</b></td><td>untik, e.g. ensi viikkoon = until next week (viikko = week)</td></tr></tbody></table>",
  "In our stories, we highlight this by translating lattialla to floor-on. These translations might look a little ugly before you get used to them, but they translate Finnish to English in a very direct way.",
  " ",
  "In the following image, you can see an example of each ending in a more visual way:",
  "<img src=\"/articles/image1_endings.png\" alt=\"Endings overview\" />",
  "<b>EXAMPLE</b><br>Kissa on lattialla.<br>Cat is floor-on.",
  "Another example for the word “in”:",
  "<b>EXAMPLE</b><br>Kissa on laatikossa.<br>Cat is box-in.",
  "In summary so far on = -lla and in = -ssa, but the translation might also be on = -llä and in = -ssä, depending on the thing that a cat is on or in at the moment.",
  "<b>EXAMPLE</b><br>Kissa on pöydällä.<br>Cat is table-on.",
  "Note that table = pöytä, but the word changes to pöydä-, when combined with an ending. Don’t worry too much about this morphing of words for now.",
  "<b>EXAMPLE</b><br>Kissa on vedessä.<br>Cat is water-in.",
  "Here, we can take note that vesi = water, changes quite a bit to vede-. And, perhaps less relevantly, that most cats dislike being in water.",
  "<b>From-on, from-in, onto and into</b>",
  "Another difference to English and related languages is that from and to don’t have their own corresponding endings. From and to are always combined with on and in. Here’s the summary of these endings:",
  "-lta, -ltä = from on<br>-lle = onto<br>-sta, -stä = from in<br>-**n = into, where the ** denotes a long double vowel. The vowel to be used depends on the word.",
  "<b>EXAMPLES</b><br>Kissa hyppäsi lattialta<br>Cat jumped floor-from_on",
  "Kissa hyppäsi lattialle<br>Cat jumped floor-onto",
  "Kissa tuli laatikosta.<br>Cat came box-from_in",
  "Kissa meni laatikkoon.<br>Cat went box-into.",
  "We have also highlighted the verb endings hyppäsi = jumped, even though they are not the topic of this very article.",
  "Then a few more examples, where the word changes:",
  "<b>EXAMPLES</b><br>Kissa hyppäsi pöydältä<br>Cat jumped table-from_on",
  "Kissa hyppäsi pöydälle<br>Cat jumped table-onto",
  "Kissa tuli vedestä.<br>Cat came water-from_in",
  "Kissa meni veteen.<br>Cat went water-into.",
  "Pöytä = table becomes pöydä- again. But notice how vesi = water has a more complicated way of changing.",
  "As in English, in, on, from etc are also used in more abstract contexts. Here are a few examples:",
  "<b>EXAMPLES</b><br>Minulla on kissa.<br>I-on have cat.<br>I have a cat.",
  "Kello kolmelta.<br>Clock three-from_on.<br>At three o’clock.",
  "Tämä on minulta sinulle.<br>This is me-from_on you-onto.<br>This is from me to you.",
  "Se päätettiin kokouksessa.<br>It decided-was meeting-in.<br>It was decided at the meeting.",
  "As in English, it is hard to fully explain why a certain ending is used.",
];

export default article1;
