export const quizQuestions = [
  { fi: "bibliotechnaya karta - библиотечная карта", answer: "Library card", options: ["Library card", "Membership key", "Student permit"] },
  { fi: "udostoverenie lichnosti - удостоверение личности", answer: "Identity document / ID", options: ["Identity document / ID", "Address certificate", "Insurance form"] },
  { fi: "voditelskie prava - водительские права", answer: "Driver's license", options: ["Driver's license", "Passport photo", "Residence permit"] },
  { fi: "sotrudnik - сотрудник", answer: "Clerk / service employee", options: ["Clerk / service employee", "Customer", "Security guard"] },
  { fi: "koshelek - кошелек", answer: "Wallet", options: ["Wallet", "Backpack", "Drawer"] },
  { fi: "mezhdu polkami - между полками", answer: "Between the shelves", options: ["Between the shelves", "By the entrance", "At the register"] },
  { fi: "prokhod - проход", answer: "Corridor / aisle", options: ["Corridor / aisle", "Balcony", "Basement"] },
  { fi: "afisha - афиша", answer: "Poster", options: ["Poster", "Receipt", "Timetable"] },
  { fi: "detektivnyy roman - детективный роман", answer: "Crime novel", options: ["Crime novel", "Travel brochure", "History essay"] },
  { fi: "tundra - тундра", answer: "Wilderness", options: ["Wilderness", "Suburb", "Harbor"] },
  { fi: "propavshiy - пропавший", answer: "Missing", options: ["Missing", "Retired", "Promoted"] },
  { fi: "kafe - кафе", answer: "Cafe", options: ["Cafe", "Bakery factory", "Warehouse"] },
  { fi: "bulochka s koritsey - булочка с корицей", answer: "Cinnamon bun", options: ["Cinnamon bun", "Savory pie", "Rice porridge"] },
  { fi: "nalichnymi - наличными", answer: "In cash", options: ["In cash", "By invoice", "By installment"] },
  { fi: "sdacha - сдача", answer: "Change (money)", options: ["Change (money)", "Salary", "Loan payment"] },
  { fi: "chek - чек", answer: "Receipt", options: ["Receipt", "Passport", "Warranty card"] },
  { fi: "musornaya korzina - мусорная корзина", answer: "Trash bin", options: ["Trash bin", "Coat rack", "Bookshelf"] },
  { fi: "dlina lyzh - длина лыж", answer: "Length of the skis", options: ["Length of the skis", "Width of the lane", "Height of the shelf"] },
  { fi: "dlina palok - длина палок", answer: "Length of the poles", options: ["Length of the poles", "Number of poles", "Pole material"] },
  { fi: "primerit - примерить", answer: "To try on", options: ["To try on", "To recycle", "To reserve"] },
  { fi: "lyzhnyy botinok - лыжный ботинок", answer: "Ski boot", options: ["Ski boot", "Ski wax", "Ski helmet"] },
  { fi: "avtomat samoobsluzhivaniya - автомат самообслуживания", answer: "Self-service machine", options: ["Self-service machine", "Coffee grinder", "Parcel locker"] },
  { fi: "shtrikh-kod - штрих-код", answer: "Barcode", options: ["Barcode", "Password", "Serial key"] },
  { fi: "skanirovat - сканировать", answer: "To scan", options: ["To scan", "To stamp", "To translate"] },
  { fi: "kachnut'sya - качнуться", answer: "To swing / lurch", options: ["To swing / lurch", "To melt", "To freeze"] },
  { fi: "opasno - опасно", answer: "Dangerously", options: ["Dangerously", "Quietly", "Carelessly"] },
  { fi: "noska - носка", answer: "Carrying", options: ["Carrying", "Borrowing", "Replacing"] },
  { fi: "neudobnyy - неудобный", answer: "Awkward / difficult", options: ["Awkward / difficult", "Cheap", "Transparent"] },
  { fi: "zakaz taksi - заказ такси", answer: "Ordering a taxi", options: ["Ordering a taxi", "Canceling a train", "Renting a bike"] },
  { fi: "avtobusnaya ostanovka - автобусная остановка", answer: "Bus stop", options: ["Bus stop", "Train depot", "Metro tunnel"] },
];

