export const quizQuestions = [
  { fi: "Kirjastokortti", answer: "Library card", options: ["Library card", "Membership key", "Student permit"] },
  { fi: "Henkilöllisyystodistus", answer: "Identity document / ID", options: ["Identity document / ID", "Address certificate", "Insurance form"] },
  { fi: "Ajokortti", answer: "Driver's license", options: ["Driver's license", "Passport photo", "Residence permit"] },
  { fi: "Virkailija", answer: "Clerk / service employee", options: ["Clerk / service employee", "Customer", "Security guard"] },
  { fi: "Lompakko", answer: "Wallet", options: ["Wallet", "Backpack", "Drawer"] },
  { fi: "Hyllyjen välissä", answer: "Between the shelves", options: ["Between the shelves", "By the entrance", "At the register"] },
  { fi: "Käytävä", answer: "Corridor / aisle", options: ["Corridor / aisle", "Balcony", "Basement"] },
  { fi: "Juliste", answer: "Poster", options: ["Poster", "Receipt", "Timetable"] },
  { fi: "Rikosromaani", answer: "Crime novel", options: ["Crime novel", "Travel brochure", "History essay"] },
  { fi: "Erämaa", answer: "Wilderness", options: ["Wilderness", "Suburb", "Harbor"] },
  { fi: "Kadonnut", answer: "Missing", options: ["Missing", "Retired", "Promoted"] },
  { fi: "Kahvila", answer: "Cafe", options: ["Cafe", "Bakery factory", "Warehouse"] },
  { fi: "Korvapuusti", answer: "Cinnamon bun", options: ["Cinnamon bun", "Savory pie", "Rice porridge"] },
  { fi: "Käteisellä", answer: "In cash", options: ["In cash", "By invoice", "By installment"] },
  { fi: "Vaihtorahat", answer: "Change (money)", options: ["Change (money)", "Salary", "Loan payment"] },
  { fi: "Kuitti", answer: "Receipt", options: ["Receipt", "Passport", "Warranty card"] },
  { fi: "Roskakori", answer: "Trash bin", options: ["Trash bin", "Coat rack", "Bookshelf"] },
  { fi: "Suksien pituus", answer: "Length of the skis", options: ["Length of the skis", "Width of the lane", "Height of the shelf"] },
  { fi: "Sauvojen pituus", answer: "Length of the poles", options: ["Length of the poles", "Number of poles", "Pole material"] },
  { fi: "Sovittaa", answer: "To try on", options: ["To try on", "To recycle", "To reserve"] },
  { fi: "Mono", answer: "Ski boot", options: ["Ski boot", "Ski wax", "Ski helmet"] },
  { fi: "Itsepalveluautomaatti", answer: "Self-service machine", options: ["Self-service machine", "Coffee grinder", "Parcel locker"] },
  { fi: "Viivakoodi", answer: "Barcode", options: ["Barcode", "Password", "Serial key"] },
  { fi: "Skannata", answer: "To scan", options: ["To scan", "To stamp", "To translate"] },
  { fi: "Heilahtaa", answer: "To swing / lurch", options: ["To swing / lurch", "To melt", "To freeze"] },
  { fi: "Vaarallisesti", answer: "Dangerously", options: ["Dangerously", "Quietly", "Carelessly"] },
  { fi: "Kantaminen", answer: "Carrying", options: ["Carrying", "Borrowing", "Replacing"] },
  { fi: "Hankala", answer: "Awkward / difficult", options: ["Awkward / difficult", "Cheap", "Transparent"] },
  { fi: "Taksin tilaaminen", answer: "Ordering a taxi", options: ["Ordering a taxi", "Canceling a train", "Renting a bike"] },
  { fi: "Bussipysäkki", answer: "Bus stop", options: ["Bus stop", "Train depot", "Metro tunnel"] },
];

