export const quizQuestions = [
  { fi: "Kuntosali", answer: "Gym", options: ["Gym", "Swimming pool", "Office"] },
  { fi: "Lämmitellä", answer: "To warm up", options: ["To warm up", "To cool down", "To stretch"] },
  { fi: "Kuntopyörä", answer: "Exercise bike", options: ["Exercise bike", "Treadmill", "Rowing machine"] },
  { fi: "Soutulaite", answer: "Rowing machine", options: ["Rowing machine", "Bench press", "Elliptical"] },
  { fi: "Juoksumatto", answer: "Treadmill", options: ["Treadmill", "Dumbbell", "Pull-up bar"] },
  { fi: "Teline", answer: "Rack / holder", options: ["Rack / holder", "Mirror", "Locker"] },
  { fi: "Hälyttää", answer: "To alarm / beep", options: ["To alarm / beep", "To light up", "To freeze"] },
  { fi: "Palohälytin", answer: "Fire alarm", options: ["Fire alarm", "Stopwatch", "Heater"] },
  { fi: "Hölkätä", answer: "To jog", options: ["To jog", "To sprint", "To jump"] },
  { fi: "Hiki", answer: "Sweat", options: ["Sweat", "Tear", "Blood"] },
  { fi: "Pyyhkiä", answer: "To wipe", options: ["To wipe", "To wash", "To dry"] },
  { fi: "Ympärilleen", answer: "Around oneself", options: ["Around oneself", "Straight ahead", "Behind"] },
  { fi: "Kyykky", answer: "Squat", options: ["Squat", "Push-up", "Lunge"] },
  { fi: "Raskas", answer: "Heavy", options: ["Heavy", "Light", "Soft"] },
  { fi: "Vapaapainot", answer: "Free weights", options: ["Free weights", "Machines", "Resistance bands"] },
  { fi: "Tanko", answer: "Barbell bar", options: ["Barbell bar", "Bench", "Plate"] },
  { fi: "Olkapäät", answer: "Shoulders", options: ["Shoulders", "Wrists", "Ankles"] },
  { fi: "Yllättävän", answer: "Surprisingly", options: ["Surprisingly", "Usually", "Barely"] },
  { fi: "Tauko", answer: "Break", options: ["Break", "Set", "Rep"] },
  { fi: "Toisto", answer: "Repetition (rep)", options: ["Repetition (rep)", "Set", "Interval"] },
  { fi: "Täristä", answer: "To shake / tremble", options: ["To shake / tremble", "To stretch", "To rest"] },
  { fi: "Käsivarsille", answer: "For the arms", options: ["For the arms", "For the back", "For the legs"] },
  { fi: "Penkkipunnerrus", answer: "Bench press", options: ["Bench press", "Deadlift", "Plank"] },
  { fi: "Levy", answer: "Weight plate", options: ["Weight plate", "Towel", "Bottle"] },
  { fi: "Rinta", answer: "Chest", options: ["Chest", "Neck", "Waist"] },
  { fi: "Vatsalihakset", answer: "Abdominal muscles", options: ["Abdominal muscles", "Calves", "Forearms"] },
  { fi: "Kulma", answer: "Angle", options: ["Angle", "Surface", "Speed"] },
  { fi: "Sarja", answer: "Set (exercise)", options: ["Set (exercise)", "Warm-up", "Cooldown"] },
  { fi: "Vahvistaa", answer: "To strengthen", options: ["To strengthen", "To weaken", "To balance"] },
  { fi: "Leuat", answer: "Pull-ups", options: ["Pull-ups", "Sit-ups", "Squats"] },
  { fi: "Kiuas", answer: "Sauna heater", options: ["Sauna heater", "Shower head", "Steam vent"] },
  { fi: "Löylyämpäri", answer: "Sauna water bucket", options: ["Sauna water bucket", "Trash bin", "Toolbox"] },
];
