export const quizQuestions = [
  { fi: "pristan - пристань", answer: "Pier / dock", options: ["Pier / dock", "Sauna bench", "Parking lot"] },
  { fi: "prorub - прорубь", answer: "Ice hole", options: ["Ice hole", "Hot spring", "Waterfall"] },
  { fi: "kollega - коллега", answer: "Coworker", options: ["Coworker", "Neighbor", "Cousin"] },
  { fi: "nervirovat - нервировать", answer: "To make nervous", options: ["To make nervous", "To warm up", "To calm down"] },
  { fi: "gipotermiya - гипотермия", answer: "Hypothermia", options: ["Hypothermia", "Flu", "Migraine"] },
  { fi: "par - пар", answer: "Steam", options: ["Steam", "Smoke", "Fog"] },
  { fi: "kolebatsya - колебаться", answer: "To hesitate", options: ["To hesitate", "To celebrate", "To whisper"] },
  { fi: "podnimatsya - подниматься", answer: "To climb", options: ["To climb", "To dive", "To float"] },
  { fi: "shag - шаг", answer: "Step", options: ["Step", "Ladder", "Staircase"] },
  { fi: "razvorachivatsya - разворачиваться", answer: "To turn around", options: ["To turn around", "To sink", "To jump"] },
  { fi: "myorznut - мёрзнут", answer: "Are freezing/feeling cold", options: ["Are freezing/feeling cold", "Are sweating", "Are shaking"] },
  { fi: "dymovaya sauna - дымовая сауна", answer: "Smoke sauna", options: ["Smoke sauna", "Steam room", "Public bath"] },
  { fi: "dymokhod - дымоход", answer: "Chimney", options: ["Chimney", "Vent", "Heater"] },
  { fi: "provetrivat - проветривать", answer: "Is ventilated/aired out", options: ["Is ventilated/aired out", "Is heated", "Is cleaned"] },
  { fi: "paltsy nog - пальцы ног", answer: "Toes", options: ["Toes", "Fingers", "Ankles"] },
  { fi: "pokalyvaet - покалывает", answer: "Tingles / stings", options: ["Tingles / stings", "Aches", "Numbs"] },
  { fi: "spokoynee - спокойнее", answer: "Calmer", options: ["Calmer", "Faster", "Louder"] },
  { fi: "opuskatsya - опускаться", answer: "To descend / lower oneself", options: ["To descend / lower oneself", "To disappear", "To dry off"] },
  { fi: "krug - круг", answer: "Circle", options: ["Circle", "Line", "Triangle"] },
  { fi: "vokrug sebya - вокруг себя", answer: "Around (oneself)", options: ["Around (oneself)", "Forward", "Under"] },
  { fi: "snezhnye - снежные", answer: "Snowy", options: ["Snowy", "Windy", "Cloudy"] },
  { fi: "medlennee - медленнее", answer: "More slowly", options: ["More slowly", "More loudly", "More carefully"] },
  { fi: "polotentse - полотенце", answer: "Towel", options: ["Towel", "Blanket", "Glove"] },
  { fi: "pivo - пиво", answer: "Beer", options: ["Beer", "Juice", "Tea"] },
  { fi: "vo vsyom - во всём", answer: "To everything / with everything", options: ["To everything / with everything", "To nowhere", "To someone"] },
  { fi: "pozzhe - позже", answer: "Later", options: ["Later", "Earlier", "Immediately"] },
  { fi: "rasslablennyy - расслабленный", answer: "Relaxed", options: ["Relaxed", "Confused", "Frustrated"] },
  { fi: "zasypat - засыпать", answer: "To fall asleep", options: ["To fall asleep", "To wake up", "To sit down"] },
  { fi: "ostanavlivatsya - останавливаться", answer: "To stop", options: ["To stop", "To accelerate", "To reverse"] },
  { fi: "strannyy - странный", answer: "Strange", options: ["Strange", "Simple", "Boring"] },
  { fi: "priyatnyy - приятный", answer: "Nice / pleasant", options: ["Nice / pleasant", "Scary", "Dirty"] },
  { fi: "snova - снова", answer: "Again", options: ["Again", "Never", "Already"] },
  { fi: "lestnitsa - лестница", answer: "Ladder (partitive plural form)", options: ["Ladder (partitive plural form)", "Stairs", "Rope"] },
  { fi: "paltsy nog - пальцы ног", answer: "Toes (partitive plural)", options: ["Toes (partitive plural)", "Hands", "Feet"] },
  { fi: "Kuusiyarvi - Куусиярви", answer: "Kuusijarvi (place name)", options: ["Kuusijarvi (place name)", "A food dish", "A company"] },
  { fi: "na pristani - на пристани", answer: "On the pier", options: ["On the pier", "In the sauna", "Under the water"] },
  { fi: "v saune - в сауне", answer: "In the sauna", options: ["In the sauna", "At home", "In the car"] },
  { fi: "zvyozdy - звёзды", answer: "Stars", options: ["Stars", "Clouds", "Birds"] },
  { fi: "luna - луна", answer: "Moon", options: ["Moon", "Sun", "Sky"] },
  { fi: "dyshat - дышать", answer: "To breathe", options: ["To breathe", "To shout", "To blink"] },
  { fi: "par - пар", answer: "Steam (partitive)", options: ["Steam (partitive)", "Ice", "Sand"] },
  { fi: "razvorachivaetsya - разворачивается", answer: "Turns around", options: ["Turns around", "Runs away", "Falls down"] },
  { fi: "bezhit - бежит", answer: "Runs", options: ["Runs", "Walks", "Drives"] }
];
