export const quizQuestions = [
  { fi: "Laituri", answer: "Pier / dock", options: ["Pier / dock", "Sauna bench", "Parking lot"] },
  { fi: "Avanto", answer: "Ice hole", options: ["Ice hole", "Hot spring", "Waterfall"] },
  { fi: "Työkaveri", answer: "Coworker", options: ["Coworker", "Neighbor", "Cousin"] },
  { fi: "Hermostuttaa", answer: "To make nervous", options: ["To make nervous", "To warm up", "To calm down"] },
  { fi: "Hypotermia", answer: "Hypothermia", options: ["Hypothermia", "Flu", "Migraine"] },
  { fi: "Höyry", answer: "Steam", options: ["Steam", "Smoke", "Fog"] },
  { fi: "Epäröidä", answer: "To hesitate", options: ["To hesitate", "To celebrate", "To whisper"] },
  { fi: "Kiivetä", answer: "To climb", options: ["To climb", "To dive", "To float"] },
  { fi: "Askel", answer: "Step", options: ["Step", "Ladder", "Staircase"] },
  { fi: "Kääntyä", answer: "To turn around", options: ["To turn around", "To sink", "To jump"] },
  { fi: "Palelevat", answer: "Are freezing/feeling cold", options: ["Are freezing/feeling cold", "Are sweating", "Are shaking"] },
  { fi: "Savusauna", answer: "Smoke sauna", options: ["Smoke sauna", "Steam room", "Public bath"] },
  { fi: "Savupiippu", answer: "Chimney", options: ["Chimney", "Vent", "Heater"] },
  { fi: "Tuuletetaan", answer: "Is ventilated/aired out", options: ["Is ventilated/aired out", "Is heated", "Is cleaned"] },
  { fi: "Varpaat", answer: "Toes", options: ["Toes", "Fingers", "Ankles"] },
  { fi: "Pistelee", answer: "Tingles / stings", options: ["Tingles / stings", "Aches", "Numbs"] },
  { fi: "Rauhallisempi", answer: "Calmer", options: ["Calmer", "Faster", "Louder"] },
  { fi: "Laskeutua", answer: "To descend / lower oneself", options: ["To descend / lower oneself", "To disappear", "To dry off"] },
  { fi: "Ympyrä", answer: "Circle", options: ["Circle", "Line", "Triangle"] },
  { fi: "Ympärilleen", answer: "Around (oneself)", options: ["Around (oneself)", "Forward", "Under"] },
  { fi: "Lumisia", answer: "Snowy", options: ["Snowy", "Windy", "Cloudy"] },
  { fi: "Hitaammin", answer: "More slowly", options: ["More slowly", "More loudly", "More carefully"] },
  { fi: "Pyyhe", answer: "Towel", options: ["Towel", "Blanket", "Glove"] },
  { fi: "Olut", answer: "Beer", options: ["Beer", "Juice", "Tea"] },
  { fi: "Kaikkeen", answer: "To everything / with everything", options: ["To everything / with everything", "To nowhere", "To someone"] },
  { fi: "Myöhemmin", answer: "Later", options: ["Later", "Earlier", "Immediately"] },
  { fi: "Rentoutunut", answer: "Relaxed", options: ["Relaxed", "Confused", "Frustrated"] },
  { fi: "Nukahtaa", answer: "To fall asleep", options: ["To fall asleep", "To wake up", "To sit down"] },
  { fi: "Pysähtyä", answer: "To stop", options: ["To stop", "To accelerate", "To reverse"] },
  { fi: "Outo", answer: "Strange", options: ["Strange", "Simple", "Boring"] },
  { fi: "Mukava", answer: "Nice / pleasant", options: ["Nice / pleasant", "Scary", "Dirty"] },
  { fi: "Uudestaan", answer: "Again", options: ["Again", "Never", "Already"] },
  { fi: "Tikkaita", answer: "Ladder (partitive plural form)", options: ["Ladder (partitive plural form)", "Stairs", "Rope"] },
  { fi: "Varpaita", answer: "Toes (partitive plural)", options: ["Toes (partitive plural)", "Hands", "Feet"] },
  { fi: "Kuusijärvi", answer: "Kuusijarvi (place name)", options: ["Kuusijarvi (place name)", "A food dish", "A company"] },
  { fi: "Laiturilla", answer: "On the pier", options: ["On the pier", "In the sauna", "Under the water"] },
  { fi: "Saunassa", answer: "In the sauna", options: ["In the sauna", "At home", "In the car"] },
  { fi: "Tähdet", answer: "Stars", options: ["Stars", "Clouds", "Birds"] },
  { fi: "Kuu", answer: "Moon", options: ["Moon", "Sun", "Sky"] },
  { fi: "Hengittää", answer: "To breathe", options: ["To breathe", "To shout", "To blink"] },
  { fi: "Höyryä", answer: "Steam (partitive)", options: ["Steam (partitive)", "Ice", "Sand"] },
  { fi: "Kääntyy", answer: "Turns around", options: ["Turns around", "Runs away", "Falls down"] },
  { fi: "Juoksee", answer: "Runs", options: ["Runs", "Walks", "Drives"] }
];
